tests/Microsoft.Identity.Web.Test/AadIssuerValidatorTests.cs
tests/Microsoft.Identity.Web.Test/AuthorityHelpersTests.cs
tests/Microsoft.Identity.Web.Test/TestConstants.cs
tests/Microsoft.Identity.Web.Test/WebApiServiceCollectionExtensionsTests.cs

- Add a test constants class
- Fix failing unit test which is fixed now that we get client_info, so we no longer fail if there is no tid in the jwt, we pull it from the claim
- I've only added on b2c authority test, but otherwise have not changed them

Prepare unit tests for more commits

---

.github/workflows/dotnetcore.yml

Adding the `FROM_GITHUB_ACTION` environment variable so that some tests don't run from GitHub actions (test requiring specific environments)

Adding an environment variable

---

src/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs
tests/B2CWebAppCallsWebApi/Client/Startup.cs
tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs

- remove unnecessary overrides and clean up `AddSignIn` and `AddWebAppCallsWebApi`
- remove obsolete methods
Part of #37

Clean up public api for web app

---

src/Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs
tests/B2CWebAppCallsWebApi/TodoListService/Startup.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Startup.cs

I propose to get rid of hybrid methods, that is provide only:
- configuration and section name
- or delegates to set the option (several delegates)
@jennyf19 : let's discuss this when/if you have time.

Proposal for the parameters of AddProtectedApi ... methods

---

src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/WebAppExtentionsTests.cs

validate v2.0 authority with web app, like we do w/web api.

---

src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs

- Updated EnsureValidAudiencesContainsApiGuidIfGuidProvided method to add on to the existing TokenValidationParameters.ValidAudiences collection instead of replacing it.
- Minor renamings.
Resolves #52

Updated EnsureValidAudiencesContainsApiGuidIfGuidProvided

---

build/template-pack-and-sign-all-nugets.yaml

This changes the build scripts to create a NuGet package containing the 3 templates:
Validated by build. See build artifacts.
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=514654&view=artifacts&type=publishedArtifacts

Jmprieur/produce templates Nuget package

---

ProjectTemplates/templates/RazorPagesWeb-CSharp/Startup.cs
ProjectTemplates/templates/StarterWeb-CSharp/Startup.cs

Why?
The startup.cs file for web apps in the templates had a comment ' Uncomment the following lines if you want your Web API ' (copy/paste issue from Web api template probably)
What?
fix this typo.
Thanks @mahoekst for reporting!

Fix typo in Web app project templates

---

src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs
src/Microsoft.Identity.Web/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs

- add tests
fix for https://github.com/AzureAD/microsoft-identity-web/issues/115

Add RedirectUri to MicrosoftIdentityOptions

---

tests/B2CWebAppCallsWebApi/Client/Views/Home/Index.cshtml
tests/B2CWebAppCallsWebApi/Client/Views/Shared/_CookieConsentPartial.cshtml
tests/WebAppCallsWebApiCallsGraph/Client/Views/Home/Index.cshtml
tests/WebAppCallsWebApiCallsGraph/Client/Views/Shared/_CookieConsentPartial.cshtml

In both sample client projects:
- moved the cookie consent bar to bottom. (Currently it completely hides the menu bar, which is a bit confusing.)
**Before:**
- updated images on home pages.
**Before:** 
**After:**

Minor fixes to samples home page

---

src/Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs

Code now preserves existing event handler when registering OnTokenValidated event handler in AddProtectedWebApiCallsProtectedWebApi.  Previous code was overwriting existing event handler meaning that logging via JwtBearerMiddlewareDiagnostics would no longer work and perhaps more seriously the OnTokenValidated event handler registered in AddProtectedWebApi (intended to "ensure that the Web API only accepts tokens from tenants where it has been consented and provisioned.")
https://github.com/AzureAD/microsoft-identity-web/issues/154

fix: #154 AddProtectedWebApiCallProtectedWebApi overwrites handler

---

src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs
src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.xml
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs
src/Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs

- Removing a useless instruction (as pointed to by @jg11jg in https://github.com/AzureAD/microsoft-identity-web/issues/154)
- Regenerating the XML comments.
- Fixing a couple of static analysis warnings

Removing a useless instruction and generating XML comments

---

tests/WebAppCallsMicrosoftGraph/MicrosoftGraphServiceExtensions.cs
tests/WebAppCallsMicrosoftGraph/Pages/Error.cshtml.cs
tests/WebAppCallsMicrosoftGraph/Pages/Index.cshtml.cs
tests/WebAppCallsMicrosoftGraph/Pages/Privacy.cshtml.cs
tests/WebAppCallsMicrosoftGraph/Program.cs
tests/WebAppCallsMicrosoftGraph/Startup.cs
tests/WebAppCallsMicrosoftGraph/WebSignInCredential.cs

I included Peter's suggestions.

some suggestions and add license info

---

.editorconfig
src/Microsoft.Identity.Web.UI/ServiceCollectionExtensions.cs
src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs

There are two ways to implement the fix. I put related comments in PR. Please give opinion. More info in #117.
Also
- Fixed warning SA1400
- Updated unit tests related to #156, #154.

Setting Access Denied path to Identity.Web.UI Access Denied page

---

.editorconfig
src/Microsoft.Identity.Web/ClientInfo.cs
src/Microsoft.Identity.Web/InstanceDiscovery/IssuerConfigurationRetriever.cs
src/Microsoft.Identity.Web/InstanceDiscovery/IssuerMetadata.cs
src/Microsoft.Identity.Web/InstanceDiscovery/Metadata.cs
src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs
src/Microsoft.Identity.Web/Resource/RegisterValidAudience.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs
src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Session/SessionTokenCacheProviderExtension.cs
tests/B2CWebAppCallsWebApi/Client/Services/TodoListService.cs
tests/B2CWebAppCallsWebApi/TodoListService/Models/TodoItem.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
tests/Microsoft.Identity.Web.Test.LabInfrastructure/LabResponse.cs
tests/Microsoft.Identity.Web.Test.LabInfrastructure/LabServiceApi.cs
tests/Microsoft.Identity.Web.Test.LabInfrastructure/LabUser.cs
tests/Microsoft.Identity.Web.Test/ClientInfoTests.cs
tests/WebAppCallsWebApiCallsGraph/Client/Services/TodoListService.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Models/TodoItem.cs

Replaced Newtonsoft.Json with System.Text.Json in projects (including samples). Plus minor spelling, warning fixes.
**Note:** Newtonsoft.Json by default does case-**insensitive** deserializaton, while System.Text.Json is case-**sensitive** by default to improve performance. In order to make it case-insensitive, we have to pass it options object to the deserializer.
Related resources:
[Try the new System.Text.Json APIs](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/)
[How to serialize and deserialize (marshal and unmarshal) JSON in .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)
[How to migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migra …

Replaced Newtonsoft.Json with System.Text.Json in projects. Plus minor misc fixes.

---

.editorconfig
src/Microsoft.Identity.Web/CertificateManagement/CertificateDescription.cs
src/Microsoft.Identity.Web/CertificateManagement/CertificateSource.cs
src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs
src/Microsoft.Identity.Web/CertificateManagement/ICertificateLoader.cs
src/Microsoft.Identity.Web/ITokenAcquisitionInternal.cs
src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs
src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs
src/Microsoft.Identity.Web/TokenAcquisition.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Session/SessionTokenCacheProviderExtension.cs
src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

Added `ForceHttpsRedirectUris` config option. When set to true, forces the `ProtocolMessage.RedirectUri` and `ProtocolMessage.PostLogoutRedirectUri` in `OnRedirectToIdentityProvider` and `OnRedirectToIdentityProviderForSignOut` event handlers, respectively, to use the HTTPS scheme.
Plus minor comment fixes.
Related issues: #175, #115.

Added ForceHttpsRedirectUris option applied to the RedirectUri and PostLogoutRedirectUri. Minor comment fixes.

---

ProjectTemplates/templates/StarterWeb-CSharp/.template.config/dotnetcli.host.json
ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/StarterWeb-CSharp/Controllers/HomeController.cs
ProjectTemplates/templates/StarterWeb-CSharp/Services/DownstreamWebApi.cs
ProjectTemplates/templates/StarterWeb-CSharp/Startup.cs
ProjectTemplates/templates/StarterWeb-CSharp/Views/Home/Index.cshtml
ProjectTemplates/templates/StarterWeb-CSharp/appsettings.json

Adding the capability of calling a Web API to the mvc2 template
To test it:
```sh
msbuild /t:pack
cd bin\Debug
dotnet new -i Microsoft.Identity.Web.ProjectTemplates.0.1.4.nupkg
mkdir test
dotnet new mvc2 --auth SingleOrg --called-api-url "https://graph.microsoft.com/beta" --called-api-scopes "user.read"
```
to un-install the templates
```
cd bin\Debug
dotnet new -u Microsoft.Identity.Web.ProjectTemplates.0.1.4.nupkg
```

Adding the capability of calling a Web API to the mvc2 template

---

ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/dotnetcli.host.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/Pages/Index.cshtml
ProjectTemplates/templates/RazorPagesWeb-CSharp/Pages/Index.cshtml.cs
ProjectTemplates/templates/RazorPagesWeb-CSharp/Services/DownstreamWebApi.cs
ProjectTemplates/templates/RazorPagesWeb-CSharp/Startup.cs
ProjectTemplates/templates/RazorPagesWeb-CSharp/appsettings.json
ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/StarterWeb-CSharp/Services/DownstreamWebApi.cs
ProjectTemplates/templates/WebApi-CSharp/.template.config/template.json
ProjectTemplates/test-templates.bat
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml

Adding the capability of calling a Web API to the webapi2 (RazorPagesWeb-CSharp) template
Contributes to #196 
To test it:
```sh
msbuild /t:pack
cd bin\Debug
dotnet new -i Microsoft.Identity.Web.ProjectTemplates.0.1.5.nupkg
mkdir test
dotnet new webapp2 --auth SingleOrg --called-api-url "https://graph.microsoft.com/beta" --called-api-scopes "user.read"
```
to un-install the templates
```
cd bin\Debug
dotnet new -u Microsoft.Identity.Web.ProjectTemplates.0.1.4.nupkg
```
Also updating the test-templates.bat file to replace `msbuild` by `dotnet build` and test for webapp2 and mvc2 calling Web APIs.

Adding calls to Web api in RazorPagesWeb-CSharp project template

---

ProjectTemplates/AspNetCoreMicrosoftIdentityWebProjectTemplates.csproj
src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj
src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj

Improving the project files.
- Removing from Microsoft.Identity.Web/MicrosoftIdentity.Web.UI the references to Microsoft.AspNetCore.Authentication.Cookies and Microsoft.Extensions.DependencyInjection which are already transitively added by ASP.NET Core.
- Updating the ClientSemVer to 0.2.0-preview in MIcrosoft.Identity.Web and Microsoft.Identity.Web.UI
- Using the same mechanism in AspNetCoreMicrosoftIdentityWebProjectTemplates.csproj as in Microsoft.Identity.Web.csproj and MicrosoftIdentity.Web.UI.csproj to align the versions;

Removing unused references and updating the ClientSemVer to 0.2.0-preview

---

src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheOptions.cs
src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs
tests/Microsoft.Identity.Web.Test.Common/TestHelpers/MsalTestTokenCacheProvider.cs

rename slidingexpiration to match what's used in asp net

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs
tests/Microsoft.Identity.Web.Test.Common/TestHelpers/HttpContextUtilities.cs
tests/Microsoft.Identity.Web.Test/Resource/ScopesRequiredHttpContextExtensionsTests.cs
tests/WebAppCallsWebApiCallsGraph/Client/Services/TodoListService.cs

Fixes #253:
- Now checks that the HttpContext is not null, otherwise throws an ArgumentNullException
- If there is no authenticated user, the HTTP response status code is set to 401
- If there is an authenticated user, the HTTP response code is set to 403 and a message tells which scopes to acquire
- Updated the tests with the new behavior.
- Updated the sample to surface an explicit message to the developer of the client.

Fixes #253: Check/decide the behavior of VerifyUserHasAnyAcceptedScope()

---

src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs

- remove static
- remove commit, as it's done automatically
for testing:
In Startup.cs:
• using Microsoft.Identity.Web.TokenCacheProviders.Session; 
•  `services.AddInMemoryTokenCaches();` replace with `services.AddSessionTokenCaches(); `
In Startup.cs, in the configure method: Configure
`app.UseSession();`
before 
`app.UseAuthentication();`
#252

fix bugs in session cache provider.

---

src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj
src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.xml
src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppServiceCollectionExtensions.cs
src/Microsoft.Identity.Web/ServiceCollectionExtensions.cs
src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/WebApiCallsWebApiAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

Issue #237.
- Added the ability to specify custom cookie options.
- Added net5.0 and netcoreapp3.1 conditionals to test project.
- Updated the file path to XML docs in the project files.
- Minor comment fixes.

Added ability to specify custom cookie options. Minor comment updates.

---

src/Microsoft.Identity.Web/CookiePolicyOptionsExtensions.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
tests/Microsoft.Identity.Web.Test/CookiePolicyOptionsExtensionsTests.cs

Updated SameSite compatibility check

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/Resource/RolesRequiredHttpContextExtensions.cs
tests/Microsoft.Identity.Web.Test/Resource/RolesRequiredHttpContextExtensionsTests.cs
tests/Microsoft.Identity.Web.Test/Resource/ScopesRequiredHttpContextExtensionsTests.cs

add app roles

---

src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs

move from IOptionsMonitor to IOptions

---

tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

Fixing the tests by calling the custom configure options properly.
These tests itself test that we call the custom event handlers set up by the dev.

Fix tests.

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj

Preview 6 was released on June 25th.
We can also set the version with a wildcard like so `Version="5.0.0-*"`

Update JwtBearer and OpenIdConnect package version to preview 6

---

src/Microsoft.Identity.Web/WebAppExtensions/WebAppCallsWebApiAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

pull client_info from the protocol message not the form

---

ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/Startup.cs
ProjectTemplates/templates/RazorPagesWeb-CSharp/appsettings.json
ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/StarterWeb-CSharp/appsettings.json
tests/WebAppCallsMicrosoftGraph/Properties/serviceDependencies.json
tests/WebAppCallsMicrosoftGraph/Properties/serviceDependencies.local.json

Update the project templates to improve the experience for B2C applications
- policies names have a default value
- [Bug fix] the Razor (webapp2) was not adding the MicrosoftIdentityUI
- Adding a setting for the signout callback
@jennyf19 : you could create a B2C web app calling a B2C API with something like:
```shell
dotnet new webapp2 --auth IndividualB2C --aad-b2c-instance "https://fabrikamb2c.b2clogin.com" --client-id "fdb91ff5-5ce6-41f3-bdbd-8267c817015d" --domain "fabrikamb2c.onmicrosoft.com" --called-api-url "https://fabrikamb2c.onmicrosoft.com/tasks" --called-api-scopes "https://fabrikamb2c.onmicrosoft.com/tasks/read"
```
(and add the client secret)

Update the project templates to improve the experience for B2C applications

---

src/Microsoft.Identity.Web/ITokenAcquisition.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenAcquisition.cs

didn't have time to test OBO, or go in-depth to any of the linked issues just yet.

fix build warnings

---

ProjectTemplates/templates/BlazorServerWeb-CSharp/Pages/CallWebApi.razor
ProjectTemplates/templates/BlazorServerWeb-CSharp/Services/DownstreamWebApi.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Controllers/WeatherForecastController.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Services/DownstreamWebApi.cs
ProjectTemplates/templates/RazorPagesWeb-CSharp/Pages/Index.cshtml.cs
ProjectTemplates/templates/RazorPagesWeb-CSharp/Services/DownstreamWebApi.cs
ProjectTemplates/templates/StarterWeb-CSharp/Controllers/HomeController.cs
ProjectTemplates/templates/StarterWeb-CSharp/Services/DownstreamWebApi.cs
ProjectTemplates/templates/WebApi-CSharp/Controllers/WeatherForecastController.cs
ProjectTemplates/templates/WebApi-CSharp/Services/DownstreamWebApi.cs
tests/BlazorServerCallsGraph/Pages/CallWebApi.razor
tests/BlazorServerCallsGraph/Services/DownstreamWebApi.cs

#357 
I ran the `*.bat` file and things seem to work.

add async to CallWebApiAsync

---

Microsoft.Identity.Web-without-blasorwasm2-sample.sln
ProjectTemplates/templates/BlazorServerWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/BlazorServerWeb-CSharp/Services/DownstreamWebApi.cs
ProjectTemplates/templates/BlazorServerWeb-CSharp/Services/MicrosoftGraphServiceExtensions.cs
ProjectTemplates/templates/BlazorServerWeb-CSharp/Startup.cs
ProjectTemplates/templates/BlazorServerWeb-CSharp/appsettings.json
ProjectTemplates/templates/BlazorServerWeb-CSharp/wwwroot/css/site.css
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/.template.config/template.json
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/ComponentsWebAssembly-CSharp.Client.csproj
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/wwwroot/css/app.css
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Controllers/WeatherForecastController.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Program.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Services/MicrosoftGraphServiceExtensions.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Startup.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/appsettings.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.js
ProjectTemplates/templates/StarterWeb-CSharp/Controllers/HomeController.cs
ProjectTemplates/templates/StarterWeb-CSharp/appsettings.json
ProjectTemplates/templates/WebApi-CSharp/Startup.cs
build/template-nuget-pack.yaml
build/template-restore-build-MSIdentityWeb.yaml
tests/blazorwasm2/Client/blazorwasm2-singleOrg-hosted4.Client.csproj
tests/blazorwasm2/Server/blazorwasm2-singleOrg-hosted4.Server.csproj
tests/blazorwasm2/Shared/blazorwasm2-singleOrg-hosted4.Shared.csproj

- Synching the templates from ASP.NET Core (johluo/identity-web-templates-balzor)
- fixing the Startup.cs of the Web API template (AddMicrosoftWebApiCallsWebApi)
- fixing the Startup.cs of the BlazorServerWeb-CSharp\Server template (AddMicrosoftWebApiCallsWebApi)
- Adding the net5.0 client ComponentsWebAssembly target to both the blazorwasm2 template and sample
- Fixing the build pack break (Incorparating the change from @pmaytak; #365)

Fixes the build with the samples included, and fixes issues in templates

---

ProjectTemplates/templates/BlazorServerWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/.template.config/template.json
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/ComponentsWebAssembly-CSharp.Client.csproj
ProjectTemplates/test-templates.bat

Remove cases in templates as B2C does not support OBO
- (bug in Blazor templates) B2C apps don't call Microsoft Graph
- B2C Web APIs (that is webapi2 and blazowasm -hosted with B2C) don't call downstream APIs since OBO is not supported in B2C
- Updating Blazor web assembly hosted client to .NET 5.0 preview 7 (requires RuntimeIdentitier)
- Removing the cases where B2C would do an OBO in test-templates.bat

Remove cases in templates as B2C does not support OBO

---

src/Microsoft.Identity.Web/TokenAcquisition.cs

@pmaytak noticed this, thank you.

fix userflow claims in addAccounToCacheFromAuthCode

---

src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs

make aadIssuerValidator public

---

.github/workflows/dotnetcore.yml

Updated the Github build action to run build commands for different .NET versions in parallel. Also updated the framework versions to 3.1.302 and 5.0 Preview 7. [Previous run example](https://github.com/AzureAD/microsoft-identity-web/actions/runs/191003994).
Was kind of a Hackathon project / POC so that the learnings can be used for the main build pipeline. 
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy)

Parallelize Github build action

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj

#410 
I rebuild, ran the tests, and tested the dev app (web app calls web api) and no issue, so i don't think we need this. if for the distributed cache, customers can add it if needed.

remove dependency

---

src/Microsoft.Identity.Web/Constants/IDWebErrorMessage.cs
src/Microsoft.Identity.Web/ITokenAcquisition.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenAcquisition.cs

Add optional HttpResponse parameter to ReplyForbiddenWithWwwAuthenticateHeaderAsync. Handle null context.

---

ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/ComponentsWebAssembly-CSharp.Client.csproj

- replaces netcoreapp3.1 by netstandard2.1
- adds the RazorLangVersion XML element
IMPORTANT:
To debug, the server needs to be the startup project to run the template

Fixes the blazorwasm2 hosted templates:

---

ProjectTemplates/AspNetCoreMicrosoftIdentityWebProjectTemplates.csproj
ProjectTemplates/templates/BlazorServerWeb-CSharp/BlazorServerWeb-CSharp.csproj
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/ComponentsWebAssembly-CSharp.Client.csproj
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/ComponentsWebAssembly-CSharp.Server.csproj
ProjectTemplates/templates/RazorPagesWeb-CSharp/Company.WebApplication1.csproj
ProjectTemplates/templates/StarterWeb-CSharp/Company.WebApplication1.csproj
ProjectTemplates/templates/WebApi-CSharp/Company.WebApplication1.csproj
ProjectTemplates/test-templates.bat

- Updates the .csproj files for the projects templates to 0.2.3-preview
- Updates the .bat file to 0.2.3-preview
__
Tested that everything builds by:
- `dotnet pack /p:ClientSemVer=0.2.3-preview` at the root of the repo
- then
- `cd ProjectTemplates`
- `test-templates.bat`

Updating the projects for templates to 0.2.3-preview

---

src/Microsoft.Identity.Web/WebAppExtensions/WebAppAuthenticationBuilderExtensions.cs

domain_hint ingored when login_hint is set.
Break up code so that domain_hint and login_hint are treated
independently.

Fix for #415

---

src/Microsoft.Identity.Web/Constants/Constants.cs
src/Microsoft.Identity.Web/Constants/IDWebErrorMessage.cs
src/Microsoft.Identity.Web/ITokenAcquisition.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs

Checked with @hpsin and here is what we agreed to:
- Change the signature of `GetAccessTokenForUserAsync` to take a `string` (instead of a `IEnumerable<string>`) as there is only one possible string for a given resource of App Id URI AppIdUri: "AppIdUri/.default". Check that the resource ends in "./default"
- Add an additional optional parameter `tenant` to support this scenario, and verify that this tenant is not organizations (and of course common and consumers, which don't make sense)
```CSharp
public async Task<string> GetAccessTokenForAppAsync(string scope, string? tenant = null)
```

Make GetTokenForAppAsync less confusing and allow to pass tenantId #413

---

src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs

Suppressing the warnings as the httpContext will not be null in this case

fix warnings from earlier PR.

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityAppCallingWebApiAuthenticationBuilder.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

Add an options delegate for methods that add caches.

---

src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiOptions.cs
src/Microsoft.Identity.Web/MicrosoftGraph/MicrosoftGraphOptions.cs
tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

we need to have more extensive integration tests, but we'll do that in the fundamentals section.

add basic unit tests for graph and downstream web api

---

src/Microsoft.Identity.Web/MicrosoftGraph/TokenAcquisitionCredentialProvider.cs

When adding Authorization header to Graph requests, space was missing, so requests weren't going through.

Fix for Authorization header format in Graph calls

---

.github/workflows/codeql-analysis.yml

Removed push and PR triggers.
Added schedule trigger to run every day at 4am UTC.
(Reference](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events)
> Scheduled workflows run on the latest commit on the default or base branch.

Update CodeQL task to run on schedule

---

src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs
tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Web.Test/AzureADB2COpenIDConnectEventHandlersTests.cs

fix for https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/399
and for https://github.com/AzureAD/microsoft-identity-web/issues/467

set response type to just idToken for web app only scenario in b2c

---

build/build.md
build/template-pack-and-sign-all-nugets.yaml

The release build does not produce NuGet packages for the Microsoft.Identity.Web.Microsoft.Graph and Microsoft.Identity.Web.Microsoft.Graph 
This PR adds this ability

Adding the missing NuGet packages to the release build

---

src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs
src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiOptions.cs
src/Microsoft.Identity.Web/ITokenAcquisition.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenAcquisition.cs
src/Microsoft.Identity.Web/TokenAcquisitionOptions.cs
tests/IntegrationTests/IntegrationTestService/Controllers/WeatherForecastController.cs
tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForUserIntegrationTests.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

need to test, so marking as draft.

add token acquisition options

---

ProjectTemplates/configuration.json
ProjectTemplates/templates/WebApi-CSharp/.template.config/template.json

@jmprieur i think we could release the template package & rerun that, but not run a new overall release build.

fix webapi2-b2c default su_si value

---

tests/Perf/Microsoft.Identity.Web.Perf.Client/ScalableTokenCacheHelper.cs
tests/Perf/Microsoft.Identity.Web.Perf.Client/TestRunner.cs
tests/Perf/Microsoft.Identity.Web.Perf.Client/TokenCacheHelper.cs

Jmprieur/perf with scalable Public Client Application cache in a different file for each account

Jmprieur/perf with scalable Public Client Application cache

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityAppCallingWebApiAuthenticationBuilder.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

add memory cache options

---

src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionCredentialProvider.cs

fixing bug #673 
I tried to leave it as much intact as is with the string format but personally i like this syntax more but not sure if I am missing something with the string format
```
request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", "token");
```

Removing existing authorization token 

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/Resource/AadIssuerValidatorOptions.cs
src/Microsoft.Identity.Web/Resource/MicrosoftIdentityIssuerValidatorFactory.cs
src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/Resource/AadIssuerValidatorTests.cs
tests/Microsoft.Identity.Web.Test/Resource/HttpClientFactoryTest.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Startup.cs

initial commit for adding aadIssuerValidatorOptions

---

changelog.md

@jmprieur we have one more item to add, but thought i'd get this started as there is a lot.
A lot of the aka.ms links are not created yet, FYI, so updates to wiki + aka.ms links are the big final TODO for 1.2 release. [Note in project card](https://github.com/AzureAD/microsoft-identity-web/projects/13#card-47851295).

changelog 1.2.0

---

src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs

scopes are ignored anyway for an app-only requests, there is no reason to require them.

Do not require scopes for app only tokens

---

src/Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs
tests/Microsoft.Identity.Web.Test.Common/Microsoft.Identity.Web.Test.Common.csproj
tests/Microsoft.Identity.Web.Test.Common/TestHelpers/MsalTestTokenCacheProvider.cs

add net461 target for cache extensions

---

Classes depending on ASP.NET Core.dgml
src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs

This enables the certificates to be added to the net472 target if we want to later
(to avoid losing this change)
Also committing the DGML graph showing which classes could be exposed to net472 (with time, not a priority)

possible improvements to ms.id.web for net472

---

.github/workflows/codeql-analysis.yml
.github/workflows/dotnetcore.yml

- Use stable .NET 5.0 version.
- Update versions of GitHub actions, which also fixes some errors shown by GitHub [here](https://github.com/AzureAD/microsoft-identity-web/actions/runs/358191852).

Use stable .NET 5, update actions versions.

---

tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/Logger.cs
tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/Metrics.cs
tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/TestRunner.cs
tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/TokenCacheHelper.cs

- Added functionality to keep a record of global metrics across threads.
- Added `PersistExceptions` method to save exceptions to a file thread-safely.
- Passing cancellation tokens into `CreateStopProcessingByTimeoutTask` and `CreateStopProcessingByUserRequestTask` so they can be cancelled immediately.
- Renamed `ScalableTokenCacheHelper` to `TokenCacheHelper`.
- Moved `Log` method into `Logger` class.
[Board card](https://github.com/AzureAD/microsoft-identity-web/projects/14#card-48719139)

Update runner to persist exceptions into a file and update metrics across processes.

---

src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs
src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs
src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProviderOption.cs

When using AppOnly call with multi-tenant application, you won't be able to obtain the token for target tenant due to not being able to choose the tenant. This pull request adds support to explicitly choose tenant when obtaining an app-only token like this:
```csharp
var organization = await _microsoftGraph.Organization
.Request()
.WithAppOnly(tenant: "thenetw.org") // or tenantId
.GetAsync();
```

Add support for tenant selection when using AppOnly Microsoft Graph

---

src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs

#805 
LMK if you want this in a separate class. this class is a little weird.

add more generic consent handler

---

build/template-install-dotnet-core.yaml
build/template-install-nuget.yaml
src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs
src/Microsoft.Identity.Web/Constants/Constants.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs
tests/IntegrationTests/WebAppUiTests/WebAppUiTests.csproj

Fixes the login_hint and domain_hint challenge.
This is a complement to the fix done in https://github.com/AzureAD/microsoft-identity-web/issues/798, which was not sufficient
The issue was:
- after fixing #800, `MicrosoftIdentityConsentAndConditionalAccessHandler.ChallengeUser` was now calling `AccountController.Challenge` with the `login_hint` and `domain_hint` parameters names (that is the **OIDC** parameter names), whereas the name of the **method** parameters are `loginHint` and `domainHint`. Added 2 new constants in `Constants` for these two method parameters names.
- The `AccountController.Challenge` method was sending the `login_hint` and `domaint_hint` to the STS as **properties** whereas they should be **parameters** (this is a very subtle behavior of the OpenIdConnectMessage) …

Fixes the login_hint and domain_hint challenge

---

src/Microsoft.Identity.Web/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs
tests/WebAppCallsMicrosoftGraph/appsettings.json

Pros:
- define the loglevel in the regular logs, 
```csharp
"Logging": {
"LogLevel": {
"Microsoft.Identity.Web": "Information",
...
```
and we pick it up: 
```csharp
loglevel = configuration.GetValue<Microsoft.Extensions.Logging.LogLevel>("Logging:LogLevel:Microsoft.Identity.Web");
```
- using natural logging system for asp .net
Cons:
- seems to be mapping to a default of `Trace` even with nothing selected. We would not want MSAL logs on all the time, as this is expensive. We'd have to figure out a different option if they want logs, but not MSAL logs.
- mapping between `Microsoft.Extensions.Logging.LogLevel` and `Client.LogLevel`, and the enum values are different
- if enabling pii logs, devs will have to set this value `"EnablePiiLogging": true` in appsettings.json

doing logs via default logging

---

src/Microsoft.Identity.Web/AzureFunctionsAuthenticationHttpContextExtension.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml

Changes are in AzureFunctionsAuthenticationHttpContextExtension.cs.

Added changes to support Azure functions

---

src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Pages/Account/Error.cshtml
src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Pages/Account/Error.cshtml.cs
src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.xml
src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs
src/Microsoft.Identity.Web/ILoginErrorAccessor.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TempDataLoginErrorAccessor.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/AzureADB2COpenIDConnectEventHandlersTests.cs

Currently, if an error occurs, the message shown says to run under Development to show more details. However, this occurs even when run under Development. This change uses TempData to display the error if available, which defaults to when run under development.

Display error messages when run under Development

---

src/Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs

Our web project doesn't have OpenIdConnect set as the default AuthenticationScheme for Challenges, so this attribute is currently unusable. (We support several types of authentication schemes)
This change allows consumers to specify the AuthenticationScheme to challenge against if the login session needs to be refreshed.

Allowing AuthorizeForScopesAttribute to specify an alternate AuthenticationScheme name

---

.github/workflows/dotnetcore.yml
tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/CodeReader.cs
tools/app-provisioning-tool/tests/ProjectDescriptionReaderTests.cs
tools/app-provisioning-tool/tests/TestUtilities.cs
tools/app-provisioning-tool/tests/Tests.csproj

Enabling the unit tests to create project folders and run a dotnet new command so that they can be run in Azure DevOps
Not all tests pass, because there are issues (either in product code or in the tests)

Enabling the unit tests to create project folders and run dotnet new

---

build/release-provisioning-tool.yml

Updates the release build for the app provisioning tool to:
- ensure that all DLLs are signed.
- ensure that the Roslyn analyzers are run
Verified that the generated package contains a dotnet global too with signed DLLs 
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=735796&view=results

Update the tool's release build

---

tools/app-provisioning-tool/app-provisioning-lib/AuthenticationParameters/ApplicationParameters.cs
tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/MsalTokenCredential.cs
tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs
tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/TokenCredentialAuthenticationProvider.cs
tools/app-provisioning-tool/app-provisioning-lib/Tool/AppProvisioningTool.cs
tools/app-provisioning-tool/app-provisioning-tool/Program.cs

**Update**
Working now for everything but MSA, w/the `.../.default` scope
----
@jmprieur i have to have an account w/MFA enabled it seems. but anyway, here is the experience based on the updated error message. I thought it would be helpful for us to be able to get the actual error returned from MSAL, instead of relying on a stack trace, which might be harder to get later.
After setting up MFA, i get this error...but, it's because the template was already configured for a Microsoft tenant, when I removed the pre configuration, it worked.
When creating an MSA account via VS UI, getting an Msal Service Exception that consumers is not available.

fix error message

---

ProjectTemplates/templates/Functions-CSharp/SampleFunc.cs

for reference: https://github.com/AzureAD/microsoft-identity-web/pull/946/files#diff-af09866885576871456a2ac8d0c5c4257cbaea76c0169327aa1f38ba2acdfac6L13

remove scope attribute from the templates for azure function

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapterOptions.cs
src/Microsoft.Identity.Web/TokenCacheProviders/MeasureDurationResult.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Utility.cs
tests/Microsoft.Identity.Web.Test/L1L2CacheOptionsTests.cs
tests/Microsoft.Identity.Web.Test/L1L2CacheTests.cs
tests/Microsoft.Identity.Web.Test/TestDistributedCache.cs
tests/Microsoft.Identity.Web.Test/UtilityTests.cs

#957 
Manual testing done:
TODO:
- handle redis errors/failures - probably in a second PR

Add L1/L2 cache implementation

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs

@henrik-me 
If you want to test this, use the dev app, which has the redis cache set up already, just uncomment `//#define UseRedisCache` in `Startup.cs` of the client, and install [docker desktop](https://docs.docker.com/docker-for-windows/install/). You can start the L2, sign-in, then stop the L2 and sign-out, or just have start stopped.
From command prompt:
```shell
docker run --name my-redis -p 5002:6379 -d redis
docker exec -it my-redis sh
redis-cli
```
to stop the connection:
```shell
exit
exit
docker ps -a
docker stop [enter 1st three digits of the redis cache name]
```
Before adding the try/catch, unhandled exception and app failure:
After, we can't catch a specific exception, as there are different types of L2 caches, so we can't catch an exception specific to a distribute cache …

Add try/catch to handle L2 connection issues

---

src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapterOptions.cs
tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs

Fixes #1042 1042
-TODO - needs testing and further work, just to start discussion

L2 Cache retry initial commit

---

tools/app-provisioning-tool/README.md

I removed the `dotnet pack` step because it is no longer needed. The install step was already updated by someone to use `dotnet tool install`

removing dotnet pack, and adding link to vs doc to app-sync tool readme

---

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationTokenAcquisition.cs
src/Microsoft.Identity.Web/Constants/IDWebErrorMessage.cs
src/Microsoft.Identity.Web/ITokenAcquisition.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenAcquisition.cs
src/Microsoft.Identity.Web/TokenCacheProviders/IMsalTokenCacheProvider.cs
src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs

@DavidParks8 thanks for the suggestion of making cca not async. i think this was done back it was a sample and needed for something else...as things moved to MSAL, we were able to remove that functionality out of id web. @jmprieur

make cca creation not async

---

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationTokenAcquisition.cs
src/Microsoft.Identity.Web/HttpContextExtensions.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs

There were some cases where highly multithreaded environments could cause issues due to non thread-safe code. This PR attempts to resolve the thread safety issues with an eye on maintaining performant execution.

Fix thread safety issues in TokenAcquisition classes

---

src/Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs

small clean up in claims principal

---

ProjectTemplates/configuration.json
ProjectTemplates/templates/BlazorServerWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/BlazorServerWeb-CSharp/appsettings.json
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/.template.config/template.json
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/Program.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/appsettings.json
ProjectTemplates/templates/Functions-CSharp/.template.config/template.json
ProjectTemplates/templates/Functions-CSharp/appsettings.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/appsettings.json
ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/StarterWeb-CSharp/appsettings.json
ProjectTemplates/templates/WebApi-CSharp/.template.config/template.json
ProjectTemplates/templates/WebApi-CSharp/appsettings.json
ProjectTemplates/templates/Worker-CSharp/.template.config/template.json
ProjectTemplates/templates/Worker-CSharp/appsettings.json

I think I found all the discrepancies w/domain, but have not built all the templates yet.

fix domain issue for other templates

---

ProjectTemplates/configuration.json
ProjectTemplates/templates/BlazorServerWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/BlazorServerWeb-CSharp/appsettings.json
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/.template.config/template.json
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/Program.cs
ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/appsettings.json
ProjectTemplates/templates/Functions-CSharp/.template.config/template.json
ProjectTemplates/templates/Functions-CSharp/appsettings.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/RazorPagesWeb-CSharp/appsettings.json
ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json
ProjectTemplates/templates/StarterWeb-CSharp/appsettings.json
ProjectTemplates/templates/WebApi-CSharp/.template.config/template.json
ProjectTemplates/templates/WebApi-CSharp/appsettings.json
ProjectTemplates/templates/Worker-CSharp/.template.config/template.json
ProjectTemplates/templates/Worker-CSharp/appsettings.json

The ASP.NET 5.0 templates use the following value for the "Domain": "qualified.domain.name"
and this is the value recognized by msidentity-app-sync.
We need to check if the same does not need to be changed in the other web app templates (mvc, webapp, and blazorserver)

Fix issue with .NET Core 3.1 project template domain value, not the same as .NET 5.0 / not recognized by msidentity-app-sync

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
src/Microsoft.Identity.Web/TokenAcquisition.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs

@jmprieur have only tested sign-in (obviously, to start), but thought you might be interested as well.
#470

update to msal4.30 + pkce support

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj

Azure.Identity 1.3.0 [fixed some issues causing auth timeouts](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/CHANGELOG.md#130-2020-11-12) when working locally in Visual Studio. Microsoft.Identity.Web 1.9.2 still uses 1.2.3. The reason for the errors is not immediately obvious because of a misleading reference to Azure CLI.
The fix is to upgrade to Azure.Identity 1.3.0.

Fix Visual Studio authenication timeout errors

---

src/Microsoft.Identity.Web/JwtBearerMergedOptions.cs
src/Microsoft.Identity.Web/MergedOptions.cs

add .Clone() for roles bug

---

src/Microsoft.Identity.Web/MergedOptions.cs

fix for response type in mergedoptions

---

src/Microsoft.Identity.Web/Resource/RequiredScopeAttribute.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/TodoListController.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json

Fixes https://github.com/AzureAD/microsoft-identity-web/issues/1223 and https://github.com/AzureAD/microsoft-identity-web/issues/1036

fix scope attribute

---

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationInformation.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

Fixes #1163 based on updates from EasyAuth people

Fixes #1163 (AppService authentication can declare aad or azureactivedirectory indifferently)

---

tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/CallbackController.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/TodoListController.cs

Logging every minute
More Logging in the callback:
- display the  URL to call the callback
- display the expiry of the OBO token

Adding more logging to the long running sample

---

src/Microsoft.Identity.Web/TokenCacheProviders/TokenCacheExtensions.cs
tests/Microsoft.Identity.Web.Test/CacheExtensionsTests.cs

@jmprieur idk if i like "caches" anymore...maybe just "cache"? your thoughts?

remove "s" in "caches"

---

src/Microsoft.Identity.Web/TokenCacheProviders/CacheSerializerHints.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs
src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs

#1304 
tested w/web app calls web API w/redis, so the cache key is null always.

use cache expiry

---

ProjectTemplates/test-aspnet-templates-from-nuget.bat
tools/ConfigureGeneratedApplications/Program.cs

Fixes a bug in the configuration tool so that missing
templates don't crash the tool

Add a script to make the .NET 6 template testable

---

tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/CallbackController.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/ILongRunningProcessContextFactory.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/LongRunningProcessContextFactory.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/TodoListController.cs
tests/WebAppCallsWebApiCallsGraph/TodoListService/Properties/launchSettings.json
tests/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json

This PR uses, when available, a IDistributedCache to store the mapping between the keys
of the long running processes and the tokens to use to
call OBO
Also fixes the fact that we could not start the Kestrel
apps (only IIS) for the web API

Uses a distributed cache for long running processes

---

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilder.cs

handle customer OnTokenValidated last after setting OBO token

---

src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs
tests/Microsoft.Identity.Web.Test/MicrosoftIdentityAuthenticationMessageHandlerTests.cs

We want GraphService client to support Pop.
#1355

fix authorization header used for GraphClientService requests

---

src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs

Using Microsoft Graph Client, calling WithAppOnly() or WithScopes() results in a KeyNotFoundException. In SetParameter(), the key is typeof(AuthenticationHandlerOption).ToString() which results in the name being set as "Microsoft.Graph.AuthenticationHandlerOption" while the value is actually present as "AuthenticationHandlerOption". This change retrieves the Name property of the Type which will always return only the class name which will be consistent with the name that is present in the dictionary.

Fixes a KeyNotFoundException when calling WithAppOnly(), WithScopes()

---

src/Microsoft.Identity.Web/TempDataLoginErrorAccessor.cs

This exception occurs sometimes when there are errors during login. It's not always the case but perhaps something to do with Temp Data not being cleared during debugging/testing and restarting. In any case, it's easily solved by just setting the temp data value instead of adding it.
Update: I've replaced the `ILoginErrorAccessor` with my own just see how this is caused and it's not due to Temp Data not being cleared. It ends up being called twice if you accidentally redirect to the same oicd handler address that is handling it - then the same key is added twice. Obviously not common and shouldn't actually occur (oops!) but still can be avoided by not using "Set"
Stack trace
```
ArgumentException: An item with the same key has already been added. Key: MicrosoftIdentityError …
```

Avoid exception: An item with the same key has already been added. Key: MicrosoftIdentityError

---

src/Microsoft.Identity.Web/TokenCacheProviders/TokenCacheExtensions.cs

Fixes #1390
See issue for test

Fixes #1390

---

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilder.cs

Removed context.Success() so that token is also available in ASP.NET Core.

Fix for issue 929

---

src/Microsoft.Identity.Web/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs

handle anonymous controller

---

src/Microsoft.Identity.Web/LoggingEventId.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.Logger.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs
tests/Microsoft.Identity.Web.Test.Common/TestHelpers/TestMsalDistributedTokenCacheAdapter.cs
tests/Microsoft.Identity.Web.Test/L1L2CacheTests.cs

handle neg expiry

---

src/Microsoft.Identity.Web/ClientInfo.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
src/Microsoft.Identity.Web/Util/Base64UrlHelpers.cs
tests/Microsoft.Identity.Web.Test/Base64UrlHelpersTests.cs

See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2879/ for perf numbers

Optimize Base64UrlHelpers

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj

This will speed up testing against local builds of IdentityModel.
Ideally we would include something like this file here: [dependencies.props](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/build/dependencies.props)
This will move us forward...

Use macro in csproj to define IdentityModel version

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs

There is a comment on the public class MicrosoftIdentityOptions.cs which indicates only the first certificate in the set is considered.  Reading through the code as well as looking over historical PRs, it appears this limitation was resolved.
https://github.com/AzureAD/microsoft-identity-web/issues/905
Correcting comment to save others from the same investigation.

Remove Outdated Comment on TokenDecryptionCertificates

---

src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.Logger.cs
src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web.TokenCache/TokenCacheLoggingEventId.cs
tests/Microsoft.Identity.Web.Test/L1L2CacheTests.cs
tests/Microsoft.Identity.Web.Test/TestDistributedCache.cs

ignore branch name, was from another investigation.
have tested w/redis cache manually as well.
#1566

fix l2 cache expiry

---

src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapterOptions.cs
tests/Microsoft.Identity.Web.Test/L1L2CacheTests.cs
tests/Microsoft.Identity.Web.Test/TestDistributedCache.cs

#1047 
in one sample, difference in write in one case was 10 ms vs 106 ms before fix.

add fire and forget to L2 when L1 is in use

---

src/Microsoft.Identity.Web/TokenAcquisition.cs
src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs

Fix for #1598 
The regression happened when implementing the multiple-authentication schemes.

fix user assigned managed identity

---

src/Microsoft.Identity.Web/TokenAcquisition.cs
src/Microsoft.Identity.Web/WebApiExtensions/WebApiBuilders.cs

Fixes https://github.com/AzureAD/microsoft-identity-web/issues/1615
Fixes an issue that when called from an event handler from the web API, the configuration for JwtBearer was not known

fix for handling event handlers in web APIs

---

src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.Logger.cs
src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs
src/Microsoft.Identity.Web.TokenCache/TokenCacheErrorMessage.cs
src/Microsoft.Identity.Web.TokenCache/TokenCacheLoggingEventId.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs

Fixes #1643.
**Changes**
- Clear the cache instead of throwing an exception when deserialization fails.
- Added logging related code for `MsalAbstractTokenCacheProvider`.
**Testing**
Tested with [WebAppCallsMicrosoftGraph](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/WebAppCallsMicrosoftGraph). All unit tests pass.

When deserialization fails, throw a more descriptive error.

---

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/Resource/JwtBearerEventsClaimsValidationTests.cs

Today, if a token is valid, but both:
1. Has neither Scopes nor Roles claims
2. Not authorized via ACL
Then the `JwtBearerHandler` will throw an `UnauthorizedAccessException` that looks like this:
```
System.UnauthorizedAccessException: IDW10201: Neither scope or roles claim was found in the bearer token.
at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.<>c__DisplayClass3_1.<<AddMicrosoftIdentityWebApiImplementation>b__1>d.MoveNext()
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
at …
```

Return TokenValidatedContext.Fail instead of throwing UnauthorizedAccessException in case of missing Roles / Scopes

---

tools/app-provisioning-tool/app-provisioning-lib/ProjectDescriptions/dotnet-web.json
tools/app-provisioning-tool/app-provisioning-lib/ProjectDescriptions/dotnet-webapi.json
tools/app-provisioning-tool/app-provisioning-lib/ProjectDescriptions/dotnet-webapp.json
tools/app-provisioning-tool/app-provisioning-tool/Readme.txt
tools/app-provisioning-tool/app-provisioning-tool/msidentity-app-sync.csproj

Fixes #1529 and #1708
- in .NET 6.0 the project templates for web apps and web APIs were simplified, and the content of the startup.cs moved to program.cs.
- msidentity-app-sync was looking for Microsoft.identity.web method calls in startup.cs.
- Augment the project descriptions for web apps and web APIs, so that net 6.0 project templates are supported (in addition to .NET 5.0 and netcoreapp3.1 
- Bump-up the version of the tool to 1.0.1 (it's a kind of bug fix to react to environment changes)
- Updates the Readme.md
1. Unregister the current `msidentity-app-sync` tool:
```Shell
dotnet tool uninstall --global msidentity-app-sync
```
2. In the folder where the app-provisioning.sln solution is located, pack the tool:
```Shell
dotnet pack app-provisioning.sln
```
3. Install the newly built …

Adding support for .net 6 simplified templates apps

---

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs

JwtBearerMiddlewareDiagnostics updated from singleton to transient to resolve conflicts in case of multiple authentication schemas. If the diagnostics is enabled, the events of the last one overwrite the others

IJwtBearerMiddlewareDiagnostics from singleton to transient

---

src/Microsoft.Identity.Web/TokenAcquisition.cs

fix for 1738

---

src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs
src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiGenericExtensions.cs

A `StatusCode` property was introduced on `HttpRequestException` in .NET 5.  
Populate it when throwing our own `HttpRequestException` in `DownstreamWebApi` when targeting supported frameworks.

fix: include StatusCode in HttpRequestException for .NET 5

---

src/Microsoft.Identity.Web/LoggingOptions.cs

I was going to run a release build and noticed the LoggingOptions is public, I don't think it needs to be, so marking as internal.

Make LoggingOptions internal

---

src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/TokenAcquisition/AcquireTokenOptions.cs

We should always return the interface rather than an implementation.

Change Dictionary to IDictionary

---

TokenAcquirerTests/TokenAcquirer.cs
TokenAcquirerTests/TokenAcquirerTests.csproj
TokenAcquirerTests/Usings.cs
src/Microsoft.Identity.Web.Certificateless/Certificateless.cd
src/Microsoft.Identity.Web.Certificateless/ClientAssertionDescription.cs
src/Microsoft.Identity.Web.Certificateless/ClientAssertionProviderBase.cs
src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs
src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj
src/Microsoft.Identity.Web.Certificateless/PodIdentityClientAssertion.cs
tests/Microsoft.Identity.Web.Test/ClientAssertionTests.cs

Contributes to fixing https://github.com/AzureAD/microsoft-identity-web/issues/1835 (part I: read and cache the assertion)
- Did the factorization proposed in the issue
- Updated TokenAcquirerTest as it was using the implicit usings, but this did not work across source control (Visual Studio tooling issue)
Remains to do:
- In TokenAcquisition, do a similar processing as for ManagedIdentityClientAssertion, but for PodIdentityClientAssertion.

Adding support for PodIdentity credentials

---

src/Microsoft.Identity.Web.Certificateless/PodIdentityClientAssertion.cs
src/Microsoft.Identity.Web.TokenAcquisition/ConfidentialClientApplicationBuilderExtension.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

- Removing the test slice for MSI client assertion (no longer needed)
#1835

- Integrating the PodIdentityClientAssertion to token acquisition.

---

src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/DownstreamRestApi/IAuthorizationHeaderProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition/DefaultAuthorizationHeaderProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs
tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs
tests/daemon-app/Daemon-app/Daemon-app.csproj
tests/daemon-app/Daemon-app/Program.cs

Provides a default implementation for IAuthorizationHeaderProvider and a service to implement it.
Fixes IAuthorizationHeaderProvider to have both verbs (for User and for Apps) Update the daemon sample

Provides a default implementation for IAuthorizationHeaderProvider

---

src/Microsoft.Identity.Web/WebApiExtensions/WebApiBuilders.cs

We overlooked this mis-usage of the MergedOptions after adding the PostConfiguration handlers.

Fix the MISE scenario 

---

src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/TokenAcquisition/AcquireTokenOptions.cs
src/Microsoft.Identity.Web.TokenAcquisition/DefaultAuthorizationHeaderProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirer.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisitionOptions.cs

Rename AuthenticationScheme to AuthenticationOptionsName in TokenAcquisitionOptions
(those are really a reference to named options)

Rename AuthenticationScheme to AuthenticationOptionsName

---

src/Directory.Build.props
src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs
src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj
src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web.TokenCache/InMemory/MsalMemoryTokenCacheProvider.cs
src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs
src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs
src/Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs
src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs
tests/Microsoft.Identity.Web.Test/Certificates/CertificateDescriptionTests.cs
tests/aspnet-mvc/OwinWebApp/Web.config

- Nullability contract in cache classes
- Adding missing MicrosoftExtensionsConfigurationBinderVersion in Directory.Builds.props for netstandard2.0
- Updating Web.Config for OWIN web app
- Updating CertificateDescriptionTest (to avoid obsolete constructor)

Fix a few warnings:

---

src/Microsoft.Identity.Web/MergedOptions.cs
tests/Microsoft.Identity.Web.Test/MicrosoftIdentityOptionsTests.cs

Hello :wave: @jennyf19 
I believe this PR will fix the following issue #749 where ClaimActions are not run if you alter these when setting up Microsoft.Identity.Web in configuration/options.
I have unable to test this easily with my own code project, but with ClaimActions totally missing in the MergedOptions class I would believe this is the problem that myself and others are having.
Look forward to your feedback and input
Thanks,
Warren :)

Bugfix #749  Claim Actions Missing & Not Running

---

src/Microsoft.Identity.Web/MergedOptions.cs
tests/Microsoft.Identity.Web.Test/MicrosoftIdentityOptionsTests.cs

* Add in missing ClaimActions into MergedOptions
* Add unit test to verify that the merged option for ClaimAction will appear
@jmprieur - I did some local testing

Bugfix #749  Claim Actions Missing & Not Running (#1899)

---

src/Directory.Build.props

[CVE-2022-34716 ](https://github.com/advisories/GHSA-2m65-m22p-9wjw)

address CVE-2022-34716 for Microsoft.AspNetCore.DataProtection

---

src/Microsoft.Identity.Web.Certificate/KeyVaultCertificateLoader.cs
tests/aspnet-mvc/OwinWebApp/App_Start/Startup.Auth.cs
tests/aspnet-mvc/OwinWebApp/Controllers/HomeController.cs
tests/aspnet-mvc/OwinWebApp/OwinWebApp.csproj
tests/aspnet-mvc/OwinWebApp/Web.config
tests/aspnet-mvc/OwinWebApp/appsettings.json

Fixes a race condition which could happen in OWIN apps (not ASP.NET Core)
It's not possible to call async methods from `TokenAcquisition.BuildConfidentialClientApplication`, because of the lock line 528.
s
```CSharp
if (!_applicationsByAuthorityClientId.TryGetValue(GetApplicationKey(mergedOptions), out application) || application == null)
{
lock (_applicationSyncObj)
{
application = BuildConfidentialClientApplication(mergedOptions);
_applicationsByAuthorityClientId.TryAdd(GetApplicationKey(mergedOptions), application);
}
}
```
Removing the async loading of certificate

Fix a race condition.

---

src/Microsoft.Identity.Web/MergedOptions.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs

fix for #1957 tested w/ Blazor server .NET 7 using the hot reload shared by a customer w/several browser tabs opened.

fix for claimAction and Scope with .NET 7

---

src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiOptions.cs
tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/DownstreamWebApiOptionsTests.cs
tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj

Fix for issue I created: #1970

Ensure DownstreamWebApiOptions clone includes all properties.

---

Directory.Build.props
src/Microsoft.Identity.Web.Diagnostics/Microsoft.Identity.Web.Diagnostics.csproj
src/Microsoft.Identity.Web.OWIN/Microsoft.Identity.Web.OWIN.csproj
src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj
src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config
tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj

Changing the min reference for net472 to Microsoft.Extentions 2.x as is done for .NET Standard 2.0.
Keeping net462 as it is as it would otherwise drag the whole framework

Changing the min reference for net472 to Microsoft.Extentions

---

src/Microsoft.Identity.Web.Certificateless/ClientAssertion.cs

Making ClientAssertion class public to inherit IDWeb repo on dMSI lib

Making ClientAssertion class public to inherit IDWeb repo on dMSI lib

---

.github/workflows/dotnetcore.yml
src/Microsoft.Identity.Web.Diagnostics/Diagnostics/CallerArgumentExpressionAttribute.cs
src/Microsoft.Identity.Web.Diagnostics/GlobalSuppressions.cs
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs
src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/TokenAcquisition-AspnetCore.cs
src/Microsoft.Identity.Web.TokenAcquisition/DefaultTokenAcquirerFactoryImplementation.cs
src/Microsoft.Identity.Web.TokenAcquisition/DefaultTokenAcquirerFactoryImplentation.cs
src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirerFactory.cs
src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationTokenAcquisition.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config
tests/Microsoft.Identity.Web.Test.LabInfrastructure/KeyVaultSecretsProvider.cs
tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs

Fix App service authentication:
- Add support for app tokens (if the app services authentication provided the right scopes)
- Fix the app services authentication regression in 2.x by registering IAuthorizationHeaderProvider and ITokenAcquirerFactory
- Remove a few warnings (Diagnostics, DownstreamApi)
- Refactors the implementation of ITokenAcquirerFactory to be a new class DefaultTokenAcquirerFactory (And no longer the TokenAquisitionAspNetCore class in ASP.NET Core)
- fix the ServiceCollectionExtensions accordingly
- fix the tests accordingly
- Adds a more explicit test failtures when the lab certificate is missing.
- Update the App.Config from the OWIN web app and web API

Fix App service authentication regressions in 2.x

---

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationInformation.cs

Fix the roles claims type in apps services
the issuer is v2.0, and it does not go through
Wilson's claimsTypeMapping, so the claims type
will always be "roles"
See also; https://github.com/AzureAD/microsoft-identity-web/pull/2027

app services roles

---

.gitignore
tools/app-provisioning-tool/Directory.Build.props
tools/app-provisioning-tool/README.md
tools/app-provisioning-tool/app-provisioning-lib/AuthenticationParameters/ApplicationParameters.cs
tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/CodeReader.cs
tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/CodeWriter.cs
tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/MsalTokenCredential.cs
tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs
tools/app-provisioning-tool/app-provisioning-lib/ProjectDescription/ConfigurationProperties.cs
tools/app-provisioning-tool/app-provisioning-lib/ProjectDescription/MatchesForProjectType.cs
tools/app-provisioning-tool/app-provisioning-lib/ProjectDescription/ProjectDescriptionReader.cs
tools/app-provisioning-tool/app-provisioning-lib/ProjectDescription/Replacement.cs
tools/app-provisioning-tool/app-provisioning-lib/ProjectDescriptions/dotnet-web.json
tools/app-provisioning-tool/app-provisioning-lib/Properties/Resources.Designer.cs
tools/app-provisioning-tool/app-provisioning-lib/Tool/AppProvisioningTool.cs
tools/app-provisioning-tool/app-provisioning-lib/app-provisioning-lib.csproj
tools/app-provisioning-tool/app-provisioning-tool/Program.cs
tools/app-provisioning-tool/app-provisioning-tool/msidentity-app-sync.csproj
tools/app-provisioning-tool/tests/ProjectDescriptionReaderTests.cs
tools/app-provisioning-tool/tests/TestUtilities.cs
tools/app-provisioning-tool/tests/Tests.csproj

- Update to .NET 7, and latest NuGet packages
- Add support for CIAM
- The json files can now be entirely modified (adding and removing nodes)
```sh
dotnet new web app --auth SingleOrg
dotnet add package Microsoft.Identity.Web
dotnet add package Microsoft.Identity.Web.UI
msidentity-app-sync --tenant-id mytenant.ciamlogin.com
```
For the moment, until the Graph API tenant-type returns the right value, the tenant-id needs to contain ciamlogin.com.

Add support for CIAM to the app registration tool

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

Fixes #2213

---

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationInformation.cs
src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationTokenAcquisition.cs
src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
tests/Microsoft.Identity.Web.Test/AppServicesAuthenticationInformationTests.cs

This PR corrects a typo in a method name from `SimulateGetttingHeaderFromDebugEnvironmentVariable` to `SimulateGettingHeaderFromDebugEnvironmentVariable`
There isn't more detail than that really - it's just fixing a typo; nothing more and nothing less.

fix: rename SimulateGetttingHeaderFromDebugEnvironmentVariable to SimulateGettingHeaderFromDebugEnvironmentVariable

---

tests/Microsoft.Identity.Web.Test/AccountExtensionsTests.cs

The ID.Web test in question fails when presented with a DEBUG version of MSAL because it uses an incorrect id.

Test fix for AccountID being in x.y format

---

src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs
tests/Microsoft.Identity.Web.Test/CacheExtensionsTests.cs
tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj

- Updates `MsalAbstractTokenCacheProvider.OnBeforeAccessAsync` to call Msal.Deseralize even if the read operation returned nothing.
- Fixes distributed cache logger to print correct cache entry size.
Fixes #2348, fixes #2349

Fix L2 logging. Fix L2 empty read.

---

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs

The Services.Configure line deleted also occurs in [WebApiAuthenticationBuilder](https://github.com/AzureAD/microsoft-identity-web/blob/48e4a5e9af22439ac9e633707860073bd5d4c91e/src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilder.cs#L45C1-L45C98)
The line deleted in MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs calls builder.Services.Configure which is also happening in the builder constructor itself (MicrosoftIdentityWebApiAuthenticationBuilder) with the same arguments which duplicated the configuration every time a builder was run using the CallDownstreamApi.
Testing:
- Unit tests all pass
- Succeeded running the DaemonConsoleCallingDownstreamApi sample against the MinimalWebApi sample.
Fixes …

Lozensky/fix perf issue CallDownstreamApi

---

Directory.Build.props
tests/DevApps/Directory.Build.props
tests/DevApps/aspnet-mvc/Directory.Build.props
tests/DevApps/aspnet-mvc/OwinWebApi/OwinWebApi.csproj
tests/DevApps/daemon-app/Daemon-app/Daemon-app.csproj
tests/Directory.Build.props
tools/app-provisioning-tool/Directory.Build.props

Updated lang version to use 11 across Id Web repo.
Fixes #[2351](https://github.com/AzureAD/microsoft-identity-web/issues/2351)

Updated Id Web to use lang version 11 across repo

---

src/Microsoft.Identity.Web.OWIN/OwinTokenAcquisitionHost.cs
src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/TokenAcquisitionAspnetCoreHost.cs
src/Microsoft.Identity.Web.TokenAcquisition/PrincipalExtensionsForSecurityTokens.cs
src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config
tests/DevApps/daemon-app/Daemon-app/Daemon-app.csproj
tests/DevApps/daemon-app/Daemon-app/Program.cs
tests/DevApps/daemon-app/daemon-console-calling-msgraph/Properties/launchSettings.json
tests/IntegrationTests/GraphServiceClientTests/GraphServiceClientTests.cs
tests/IntegrationTests/TokenAcquirerTests/TokenAcquirer.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
tests/Microsoft.Identity.Web.Test/PrincipalExtensionsForSecurityTokensTests.cs

In .NET 5+, we now use the DefaultTokenAcquisitionHost (the host for SDK apps) instead of the Asp.NET core one, when the service collection was not initialized by ASP.NET Core (that is the `IWebHostEnvironment` is not present in the collection.
If developers want the ASP.NET Core host, they would need to use the WebApplication.CreateBuilder().Services instead of instanciating a simple service collection.
Fixes #2371

Fix for #2371

---

src/Microsoft.Identity.Web.OWIN/Microsoft.Identity.Web.OWIN.csproj

OWIN: Remove Microsoft.AspNet.WebApi.HelpPage dependency
OWIN: Remove Microsoft.AspNet.WebApi.HelpPage dependency
The package auto copies a lot of unnecessary files to the target project, and the dependency cannot be removed while Microsoft.Identity.Web .OWIN is installed.
By installing Microsoft.Identity.Web.Owin it auto adds all these files to my project through its (seemingly) unused dependency to Microsoft.AspNet.WebApi.HelpPage:
This PR removes the dependency.
Fixes #2417 (in this specific format)

OWIN: Remove Microsoft.AspNet.WebApi.HelpPage dependency

---

src/Microsoft.Identity.Web/Resource/RegisterValidAudience.cs
src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilder.cs
tests/Microsoft.Identity.Web.Test/Resource/RegisterValidAudienceTests.cs

RegisterValidAudience needed the claims but only knew about JwtSecurityToken. This updates it to retrieve the claims from JwtSecurityToken or a JsonWebToken.
Fixes #2420

Make RegisterValidAudience aware of JsonWebToken

---

src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs

When using B2C, returned claims do not have `preferred_username` and therefore the `.Value` property throws an exception in the SecurityTokenValidated handler. This change fallbacks to just `name` claim if the original is not found and checks for empty value before adding new claim to the identity.

[OWIN] Avoid null reference in SecurityTokenValidated with B2C

---

src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs

When sessions are disabled in Web.config, Session property is null and the AuthorizationCodeReceived handler throws exception. This change fallbacks to OwinContext.Environment dictionary, because the only use of session is to hand over Client Info from one handler to another in a single request.

[OWIN] Avoid null reference when session is disabled

---

src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.HttpMethods.cs
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.HttpMethods.tt

Check all HttpResponses for success before returning to the caller.
Check all API Responses for success
Update HttpMethods to check the response for success before returning to the user.
Currently only calls that try to de-serialize were getting checked.
Issue #2426

api: Check all responses for success

---

Directory.Build.props
src/Microsoft.Identity.Web.Certificate/DefaultCredentialsLoader.cs
tests/IntegrationTests/TokenAcquirerTests/TokenAcquirer.cs

Summary of the changes
Ensure multiple requests don't attempt to load the same credentialDescription concurrently.
When a customer configures the source of a token decryption certificate in the inbound policy, SAL attempts to load the certificate from the specified source or retrieves the cached certificate if it has been loaded previously. SAL then creates an X509SecurityKey from the certificate and adds it to InboundPolicy.TokenValidationParameters.TokenDecryptionKeys if the key was not already added. This logic is executed for every incoming token validation request, and SAL utilizes ID.Web's implementation of ICredentialLoader to retrieve the certificate.
Until the certificate is cached by ID.Web (i.e., when credentialDescription.CachedValue is set), multiple parallel requests …

Introduces a lock while loading credentials from Credential Source

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirerFactory.cs

- [ X] You've read the [Contributor Guide](https://github.com/AzureAD/microsoft-identity-web/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/AzureAD/microsoft-identity-web/blob/master/CODE_OF_CONDUCT.md).
- [ X] You've included inline docs for your change, where applicable.
- [ X] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
Addition of environment variables as a source for configuration values. Placed after appsettings.config so that they can be used to override variables. Especially useful in containers.
Fixes #2480

Addition of environment variables as config source in TokenAcquirerFactory

---

Directory.Build.props
src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj

Fix build on .NET FW after #2480 and remove the "The referenced project is targeted to a different framework family" warnings
#2480

Fix build on .NET FW after #2480

---

src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs
tests/Microsoft.Identity.Web.Test/TestTokenAcquisitionHost.cs

Based on customer feedback, change the condition by which a host is used rather than another (DefaultTokenAcquisitionHost vs TokenAcquisitionAspnetCoreHost)

Fixes #2410, #2410

---

azure-pipelines.yml
build/template-install-dependencies.yaml
src/Microsoft.Identity.Web.Certificate/KeyVaultCertificateLoader.cs
tests/DevApps/WebAppCallsWebApiCallsGraph/Client/appsettings.json
tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService/Properties/launchSettings.json
tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json
tests/IntegrationTests/WebAppCallsApiCallsGraphUiTests/TestingWebAppCallsApiCallsGraphLocally.cs
tests/IntegrationTests/WebAppUiTests/UiTestHelpers.cs

Was hitting this error:
So changed the web API to use `http`, as could not get the vm to pick up the cert without manual intervention.
Had to do a few other changes, such as using a different pool, which had the managed identity enabled.

Use http instead of https

---

Directory.Build.props

It makes builds non-deterministic to rely on latest for dependencies.
This library also should use lower dependencies when possible to avoid conflicts with other library that build on this as well as applications that use this.
Fixes #2569

Fixes 2569

---

src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config

Updating OWIN apps

---

src/Microsoft.Identity.Web.TokenAcquisition/IDWebErrorMessage.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

Add a check in ID.Web to check for the presence of '&' for assertion and sub-assertion in ExtraQueryParameters dictionary.

Adding Check Against Injection Attacks

---

src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs

See issue below
Fixes https://github.com/AzureAD/microsoft-identity-web/issues/2643
Kind of clashes with https://github.com/AzureAD/microsoft-identity-web/issues/2644 but this will work at least as a short-term fix for people wanting to use WorkloadIdentity (on AKS)
An alternative approach would be a completely new class dedicated for WorkloadIdentity:
```csharp
public class WorkloadIdentityClientAssertion : ClientAssertionProviderBase
{
private readonly TokenCredential _credential;
/// <summary>
/// See https://aka.ms/ms-id-web/certificateless.
/// </summary>
/// <param name="managedIdentityClientId">ClientId of the managed identity, in case multiple identities are federated with the service account</param>
public …
```

ManagedIdentityClientAssertion: Set clientId for both ManagedIdentity and WorkloadIdentity

---

src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs
src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs

Fixes the use of `ServiceDescriptor` for containers which have keyed services present. This can be an issue on .NET 8.0 and has been reported by some users of the library here: https://github.com/AzureAD/microsoft-identity-web/issues/2604
The issue is caused by unconditional access to `ServiceDescriptor.ImplementationType` and the fix is to first check whether `ServiceDescriptor.ServiceKey` is set. If it is, we can safely ignore that descriptor.
For more information on keyed services, see the dotnet/runtime thread here: https://github.com/dotnet/runtime/issues/64427 and the PR here: https://github.com/dotnet/runtime/pull/87183.
Fixes #2604

Fix ServiceDescriptor access when Keyed Services are present

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs

Remove a block comment containing unused code and a stray semicolon

Clean up commented code, extra semicolon

---

tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs

The user assigned managed identity used in the release builds for the tests has changed.
@jennyf19 we might also want to take this in rel/v2?
running a release build to check the fix.

Replace the user assigned managed identity in tests, by another one

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

fix assertions being removed from dict before callback is executed

---

tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs
tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs

Adding CIAM CUD integration tests
Adding CIAM CUD integration tests
Fixes #2738

Adding CIAM CUD integration tests

---

.github/workflows/dotnetcore.yml
Directory.Build.props
build/template-install-dependencies.yaml
build/template-postbuild-code-analysis.yaml
src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj
src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj
src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj
src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj
src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj
tests/DevApps/Directory.Build.props
tests/Directory.Build.props
tests/E2E Tests/IntegrationTestService/IntegrationTestService.csproj
tests/E2E Tests/TokenAcquirerTests/TokenAcquirerTests.csproj
tests/E2E Tests/WebAppUiTests/B2CWebAppCallsWebApiLocally.cs
tests/E2E Tests/WebAppUiTests/WebAppUiTests.csproj
tests/Microsoft.Identity.Web.Test.Common/Microsoft.Identity.Web.Test.Common.csproj
tests/Microsoft.Identity.Web.Test.Integration/Microsoft.Identity.Web.Test.Integration.csproj
tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
tests/PerformanceTests/Microsoft.Identity.Web.Perf.Benchmark/Microsoft.Identity.Web.Perf.Benchmark.csproj
tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/Microsoft.Identity.Web.Perf.Client.csproj
tools/app-provisioning-tool/app-provisioning-lib/app-provisioning-lib.csproj

Add a net 9 target to Id Web with conditional compilation.
Successful Builds:
TargetNet9 = True (https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1281414&view=results)
TargetNet9 = False (https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1281375&view=results)

Conditionally Target NET 9 

---

src/Microsoft.Identity.Web.TokenAcquisition/DefaultTokenAcquirerFactoryImplementation.cs
tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs

DefaultTokenAcquirerFactoryImplementation now supports multiple regions and more thread safe.
- The DefaultTokenAcquirerFactoryImplementation now incorporates the region within the key string, resolving a bug wherein getting a token acquirer for a particular region could inadvertently yield a token acquirer meant for a different region. 
- Additionally, the implementation now employs a ConcurrentDictionary to manage its data, enhancing thread safety in scenarios where multiple threads may attempt to create a TokenAcquirer simultaneously.

DefaultTokenAcquirerFactoryImplementation use ConcurrentDictionary

---

src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj
src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj
src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs

Fixes warning NU1504: Duplicate 'PackageReference' items found in Microsoft.Identity.Web.GraphServiceClient.csproj and Microsoft.Identity.Web.GraphServiceClientBeta.csproj post targeting NET9.
Passing build: https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1288661&view=results
Fixes #2748

Fix Graph Version Warning

---

src/Microsoft.Identity.Web.TokenAcquisition/Constants.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

Add a clause to process the error code for a certificate outside of the validity window.

Process error AADSTS1000502 - expired certificate

---

src/Microsoft.Identity.Web.Certificate/CertificateDescription.cs
src/Microsoft.Identity.Web.Certificate/CertificateLoaderHelper.cs
src/Microsoft.Identity.Web.Certificate/FromPathCertificateLoader.cs
src/Microsoft.Identity.Web.Diagnostics/OsHelper.cs

- do not use EphemeralKey on MacOS for loading certs. Instead, use the user key. 
{Detail}
Fixes #1976

Do not use EphemeralKey on MacOS for loading certs

---

changelog.md
src/Microsoft.Identity.Web/AuthorityHelpers.cs
tests/Microsoft.Identity.Web.Test/AuthorityHelpersTests.cs

The purpose of the issue #2697 was to respect user-provided query params. The goal is to actually parse the query params from options.Authority into options.ExtraQueryParams, rather than add options.ExtraQueryParams to the authority.

Revert "add queryParams when building authority (#2826)"

---

src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config

Fixes #2849 
Tested manually with the 2 OWIN applications and the daemon app on Target framework 4.8

In AddTokenAcquisition(singleton:true) an implementation of TokenAcquirerFactory (for ASP.NET Core 2.x on .NET FW)

---

src/Microsoft.Identity.Web.TokenAcquisition/BaseAuthorizationHeaderProvider.cs
tests/E2E Tests/TokenAcquirerTests/BaseAuthorizationHeaderProviderTest.cs

It can be derived by extensions that want to leverage IdWeb for Bearer and Pop but process their own protocols
Fixes #2856

Adding a base class for AuthorizationHeaderProvider for extensibility

---

changelog.md
src/Microsoft.Identity.Web/AuthorityHelpers.cs
src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs
src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/AuthorityHelpersTests.cs
tests/Microsoft.Identity.Web.Test/TheoryDataBase.cs

Respect user-provided authority queries and add to options.ExtraQueryParams

---

src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

Altered how the metadataAddress is set to prevent overwriting the correct value.
Fixes #2752

Fix metadata address creation when using AddMicrosoftIdentityWebApp

---

Directory.Build.props
benchmark/TokenAcquisitionBenchmark.cs
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs
src/Microsoft.Identity.Web.GraphServiceClient/GraphAuthenticationProvider.cs
src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition/BaseAuthorizationHeaderProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition/DefaultAuthorizationHeaderProvider.cs
tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
tests/Microsoft.Identity.Web.Test/BaseAuthorizationHeaderProviderTest.cs
tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/CaeTests.cs

What?
- Implements IAuthorizationHeaderProvider.GetAuthorizationHeaderAsync in DefaultAuthorizationHeaderProvider
- Updates DownstreamApi, MicrosoftGraph, GraphServiceClient and BaseAuthorizationHeaderProvider to use the new higher level API that can create a header for on-behalf-of an app or user instead of separate APIs (GetAuthorizationHeaderForAppAsync and GetAuthorizationHeaderForUserAsync). There is no change to the existing DevEx.
- Adds ConfigureAwait which was previously missing for some async calls
Why?
This is being done to accommodate 1P specific protocols.

Implements GetAuthorizationHeaderAsync to support 1P specific scenarios

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

The AddDstsHttpClientFactory() will create the dSTS prefer IPv6 http client and register the DstsHttpClientFactory.
This change will enforce the token acquisition flow to use dSTS http client to process http request.

Use registered IMsalHttpClientFactory if it is exist

---

Directory.Build.props
benchmark/TokenAcquisitionBenchmark.cs
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs
src/Microsoft.Identity.Web.GraphServiceClient/GraphAuthenticationProvider.cs
src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition/BaseAuthorizationHeaderProvider.cs
src/Microsoft.Identity.Web.TokenAcquisition/DefaultAuthorizationHeaderProvider.cs
tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
tests/Microsoft.Identity.Web.Test/BaseAuthorizationHeaderProviderTest.cs
tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/CaeTests.cs
tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/DownstreamApiTests.cs

Cherry picks PR #2896 from rel/v2

Cherry picks PR #2896

---

src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs

Makes `MicrosoftIdentityWebAppAuthenticationBuilder` extensible by users by giving its `OpenIdConnectScheme` property a public getter.
The following changes:
```cs
private string OpenIdConnectScheme { get; set; }
```
becomes
```cs
public string OpenIdConnectScheme { get; private set; }
```
Fixes #2638

Make MicrosoftIdentityWebAppAuthenticationBuilder's OpenIdConnectScheme publicly gettable

---

Directory.Build.props
src/Microsoft.Identity.Web.Certificate/KeyVaultCertificateLoader.cs
src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs
src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj

For Azure.Identity credential scenarios where Managed Identity is needed, we should use `ManagedIdentityCredential` rather than `DefaultAzureCredential`.
`DefaultAzureCredential` now has more aggressive "fail fast" behavior which could lead to timeouts for token requests.

Use ManagedIdentityCredential instead of DefaultAzureCredential for FIC scenario (PR for ID.Web 3.x)

---

src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs
src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj

See https://github.com/AzureAD/microsoft-identity-web/pull/2813

Fix for #2893 - do not attempt WorkloadIdentityCredential for MSI FIC (for Id.Web v2)

---

src/Microsoft.Identity.Web.Azure/Microsoft.Identity.Web.Azure.csproj
src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj
src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj
src/Microsoft.Identity.Web.Diagnostics/Microsoft.Identity.Web.Diagnostics.csproj
src/Microsoft.Identity.Web.DownstreamApi/Microsoft.Identity.Web.DownstreamApi.csproj
src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj
src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj
src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj
src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj
src/Microsoft.Identity.Web.OWIN/Microsoft.Identity.Web.OWIN.csproj
src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj
src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj
src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj
src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj

Ensures that the README file is correctly displayed on NuGet.org.

Update CSPROJ with README

---

Directory.Build.props

IdWeb 3.0.1 is not compatible with Abstractions 7. This sets a bound on the allowed version.

Set upper bound on Abstractions

---

tests/Microsoft.Identity.Web.Test.Common/Mocks/MockHttpMessageHandler.cs
tests/Microsoft.Identity.Web.Test/CacheExtensionsTests.cs

Revert some of the test changes introduces in #2950
That change introduced test instability
fixes #2964

Fix test instability

---

tests/Microsoft.Identity.Web.Test.Common/Mocks/MockHttpClientFactory.cs
tests/Microsoft.Identity.Web.Test.Common/Mocks/MockHttpMessageHandler.cs
tests/Microsoft.Identity.Web.Test/MsAuth10AtPopTests.cs

Use existing pattern in cache extensions test in
MsAuth10AtPopTests
Continuation of #2971 
Fixes test instability introduced by #2950

Fix AT POP tests

---

Directory.Build.props
NuGet.Config
build/template-restore-build-MSIdentityWeb.yaml
src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj
src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj
src/Microsoft.Identity.Web.OWIN/Microsoft.Identity.Web.OWIN.csproj
src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj
src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj

Ensures that the same build variable name (`MicrosoftIdentityWebVersion`) is used both for the version of the library itself, and in the libraries that take a dependency on Wilson. This name was already used in other libraries. This becomes the way to set the version in Release builds.

[test] updates for one build

---

tests/Microsoft.Identity.Web.Test.Integration/Microsoft.Identity.Web.Test.Integration.csproj

Ensure that SimulateOidc is built before IntegrationTests (that use it)

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs

AzureRegion was used while calculating key in DefaultTokenAcquirerFactoryImplementation but not in TokenAcquisition.cs file. Now the GetKey method in TokenAcquisition calls the method with same name in DefaultTokenAcquirerFactoryImplementation . This will ensure that both methods rely on the same set of attributes while creating key.
Fixes #{3001194} (https://identitydivision.visualstudio.com/Engineering/_workitems/edit/3001194)

Use AzureRegion while calculating key

---

tests/Microsoft.Identity.Web.Test/CacheExtensionsTests.cs

Just a unit test, no product change.

Add a test around TokenCache GetCacheKey customization

---

tests/Microsoft.Identity.Web.Test/AuthorityHelpersTests.cs
tests/Microsoft.Identity.Web.Test/MsalTokenCacheProviderTests.cs

Not as much of a problem in idweb as compared to the other repos :)

add disable discover enumeration = true for theory tests

---

tests/E2E Tests/WebAppUiTests/B2CWebAppCallsWebApiLocally.cs
tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs
tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForUserIntegrationTests.cs
tests/Microsoft.Identity.Web.Test/CacheExtensionsTests.cs
tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs

According to this guidance from [XUnit](https://xunit.net/xunit.analyzers/rules/xUnit1030), using `ConfigureAwait(false)` in tests can lead to issues with synchronization and parallelization. In local testing removing ConfigureAwait seemed to work as I could repro flakiness locally in about 1-3 attempts but post-fix there was no observed flakiness locally after 14 attempts.
That doesn't guarantee it fixes the build pipeline, but it looks promising so far. There is a risk of recurrence in the build pipeline even if this method is successful as I only edited tests that were observed as flaky in the last two weeks. Therefore, if a test still using ConfigureAwait(false) triggers flakiness but hasn't been failing itself, it would still be capable of breaking the build.

Removed ConfigureAwait(false) from flaky tests

---

tests/Microsoft.Identity.Web.Test.Common/TestHelpers/TestMsalDistributedTokenCacheAdapter.cs
tests/Microsoft.Identity.Web.Test/AzureADB2COpenIDConnectEventHandlersTests.cs
tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs
tests/Microsoft.Identity.Web.Test/Certificates/WithClientCredentialsTests.cs
tests/Microsoft.Identity.Web.Test/ClientAssertionTests.cs
tests/Microsoft.Identity.Web.Test/L1L2CacheTests.cs
tests/Microsoft.Identity.Web.Test/MicrosoftIdentityAuthenticationMessageHandlerTests.cs
tests/Microsoft.Identity.Web.Test/Resource/JwtBearerEventsClaimsValidationTests.cs
tests/Microsoft.Identity.Web.Test/Resource/JwtBearerMiddlewareDiagnosticsTests.cs
tests/Microsoft.Identity.Web.Test/Resource/OpenIdConnectMiddlewareDiagnosticsTests.cs
tests/Microsoft.Identity.Web.Test/Resource/RequiredScopeOrAppPermissionPolicyTests.cs
tests/Microsoft.Identity.Web.Test/Resource/RequiredScopePolicyTests.cs
tests/Microsoft.Identity.Web.Test/UtilityTests.cs
tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs

Per [the guidance in the XUnit docs](https://xunit.net/xunit.analyzers/rules/xUnit1030), removing await configurations can cause unexpected behavior as the test framework is not able to control the awaited processes without these configurations. This has led to flaky tests through intermittent race conditions.

removed ConfigureAwait(false) from all tests

---

Directory.Build.props
tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs
tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/DownstreamApiTests.cs
tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs

trying fix for encryption test

---

tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs

Fix TokenCacheEncryption tests in .NET 9

---

.editorconfig

Closes #3050 
Edit `.editorconfig` to align with SAL, Wilson, MISE.

Align editor config with other libraries

---

tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs

Fix reflection in `MemoryCache` tests to support both versions seen in .NET 9 RCs. In RC1 there was one entry collection while in RC2 it was split back out as seen in previous versions of .NET: https://github.com/dotnet/runtime/commit/7ca789e12cbd9c1da8a9de68448d9835e5aa9784

Fix reflection in MemoryCache tests to support both versions seen in .NET 9 RCs

---

.github/workflows/dotnetcore.yml
tests/Directory.Build.props

Update GitHub Action to run unit tests:
- Fixes test filters, only .NET 6 tests were running
- Updates task versions to the latest

Update GitHub Action to run unit tests

---

build/template-install-dependencies.yaml
build/template-onebranch-release-build.yaml
build/template-pack-nuget.yaml
build/template-restore-build-MSIdentityWeb.yaml

**Goal:**
When building internally, use an internal Nuget feed, instead of nuget.org
**Did you know?** 
When you are accessing an artifact's feed in the same project, you don't need to specify a service connection in Azure DevOps, NuGetAuthenticate@1 without it a service connection works. If you specify a service connection, you'll need some credentials, like a PAT that will need to be rotated ...
**What** this PR does:
This PR modifies the build scripts to just run nuget authenticate (no service connection), and removes the Nuget.org source, and adds the IDDP source

Fix DevEx and IDDP builds

---

tests/DevApps/ciam/myWebApi/Program.cs
tests/DevApps/ciam/myWebApi/Properties/launchSettings.json
tests/DevApps/ciam/myWebApi/myWebApi.csproj
tests/DevApps/daemon-app/minimal-web-api/MinimalWebApi.csproj
tests/DevApps/daemon-app/minimal-web-api/Program.cs
tests/DevApps/daemon-app/minimal-web-api/Properties/launchSettings.json

Remove swagger dependencies

---

.github/dependabot.yml

Added grouping to dependabot config so PRs can contain multiple suggestions. The groupings are minor and patch updates with a security designation and minor and patch updates without a security designation. Major version updates will all still get their own PRs
Additionally, it will label grouped PRs with whether the updates are security-related or not based on the group names of security and notsecurity

Grouping Dependabot Updates

---

.github/workflows/dotnetcore.yml
tests/Directory.Build.props
tests/E2E Tests/GraphServiceClientTests/GraphServiceClientTests.csproj
tests/E2E Tests/NET 7 tests/IntegrationTests/IntegrationTests.csproj
tests/E2E Tests/TokenAcquirerTests/TokenAcquirerTests.csproj
tests/E2E Tests/WebAppUiTests/WebAppUiTests.csproj
tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj

Use GitHub Actions to display a code coverage report in the Actions summary and in a PR comment. This does not show a difference based on the proposed code changes. That is a future work item.
Closes #3048 
The coverage report displayed in the comment is also available in the summary of the testing action:
Show all checks (if all have passed and it's collapsed) -> Run unit tests: details -> Summary

display code coverage as PR comments

---

changelog.md

Update changelog.md for 3.3.0

---

changelog.md

Update changelog.md to fix release 3.2.2 which had a breaking change
Fixes #3101
This broke a number of partners using FIC+MSI with MSAL.NET
cc: @bgavrilMS

Update changelog.md to fix release 3.2.2 which had a breaking change

---

tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs

The certificate that was used was not present on the build machine. Just using a certificate that is used by other tests.

Fixing the ROPC test that broke the build

---

Directory.Build.props
src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net462/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net472/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net6.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net7.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net8.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/netstandard2.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionTests.cs

Use `AppHomeTenantId` for acquiring app token when `TenantId` is not tenant. https://github.com/AzureAD/microsoft-identity-web/issues/3121

Use AppHomeTenantId for acquiring app token when TenantId is not tenant

---

src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net9.0/PublicAPI.Unshipped.txt

Related to #3130 
The new API was not declared for net 9.

Declare ROPC extensions in net 9 API

---

src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net462/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net472/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net6.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net7.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net8.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/netstandard2.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisitionExtensionOptions.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisitionExtensions.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAddInTests.cs

Need to pass the user to the extensibility to ensure the parameters can be updated before token request on basis of the user.
Fixes #3139

Update the extensibility to add user

---

.github/workflows/aot-check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dotnetcore.yml
Directory.Build.props
build/template-install-dependencies.yaml
build/template-postbuild-code-analysis.yaml
build/test-aot.ps1
src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj
src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj
tests/DevApps/Directory.Build.props
tests/Directory.Build.props
tests/E2E Tests/IntegrationTestService/IntegrationTestService.csproj
tests/E2E Tests/TokenAcquirerTests/TokenAcquirerTests.csproj
tests/E2E Tests/WebAppUiTests/WebAppUiTests.csproj
tests/Microsoft.Identity.Web.Test.Common/Microsoft.Identity.Web.Test.Common.csproj
tests/Microsoft.Identity.Web.Test.Integration/Microsoft.Identity.Web.Test.Integration.csproj
tests/PerformanceTests/Microsoft.Identity.Web.Perf.Benchmark/Microsoft.Identity.Web.Perf.Benchmark.csproj
tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/Microsoft.Identity.Web.Perf.Client.csproj

Update to .NET 9 GA. Update some test dependencies.

---

src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs
tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs

Why?
This PR ensures TokenAcquisition services are registered only as singletons if the `isTokenAcquisitionSingleton` flag is true and removes any previously added scoped TokenAcquisition services when TokenAcquirerFactory is not used.
 
{Detail}
#3157

Ensure Singleton registration for TokenAcquisition Services when TokenAcquirerFactory is null

---

.github/workflows/dotnetcore.yml

Related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2983
Until code coverage report is configured ideally, do not post a comment with the report each time a push is made.
The report is still visible in the summary section of the action that runs unit tests.

Disable Coverage PR comments

---

src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net462/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net472/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net6.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net7.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net8.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/netstandard2.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

PrepareAuthorityInstanceForMsal modifies a shared options object, we shouldn't do that.

Dont modify the merged options when building the confidential client

---

src/Microsoft.Identity.Web.Diagnostics/IdHelper.cs
src/Microsoft.Identity.Web.Diagnostics/PublicAPI/net462/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.Diagnostics/PublicAPI/net472/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.Diagnostics/PublicAPI/net6.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.Diagnostics/PublicAPI/net7.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.Diagnostics/PublicAPI/net8.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.Diagnostics/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.Diagnostics/PublicAPI/netstandard2.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs
src/Microsoft.Identity.Web.DownstreamApi/PublicAPI/net462/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.DownstreamApi/PublicAPI/net472/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.DownstreamApi/PublicAPI/net6.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.DownstreamApi/PublicAPI/net7.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.DownstreamApi/PublicAPI/net8.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.DownstreamApi/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.DownstreamApi/PublicAPI/netstandard2.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/Constants.cs
tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/DownstreamApiTests.cs

See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4864 for details. Goal is to identify zero-touch APIs
1. Add "caller-sdk-id" and "caller-sdk-version" as extra QP. Note that these differentiate an API used, in this case `DownstreamAPI`. Afaik this is the only zero-touch API. 
This information will be captured via OTEL and via Http telemetry by MSAL.
Alternatives we can consider:
- use the existing http header `x-client-brkver`
- use a different http header, like `x-telem-last` which is currently out of use
2. Not entirely sure how to add unit tests. Was thinking of moving the logic to `MergeOptions` but it does not seem to be called from all `CallApi` methods?

Use ExtraQP to inject telemetry SDK ID

---

Directory.Build.props
src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj
src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj
tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs

Removed now un-needed reference
Fixes #3167

Fix 3167 (package downgrade when referencing IdentityModel.Tokens from dev)

---

build/template-publish-and-cleanup.yaml

With the new task, I've configured the build to:
- fail if the number of warnings has increased since the previous build - no new warnings!
- show warning statistics to show the changes in number of warnings grouped by task/code file/object
I have not selected this option:
- Force fewer warnings 
- Allow Variance - we don't want the number of warnings to creep up. 
Build Quality Checks Warnings Policy documentation: https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/WarningsPolicy.md#evaluateTaskWarnings

Add Warning Quality Check Build Task 🔨

---

Directory.Build.props
src/Microsoft.Identity.Web.Certificate/Base64EncodedCertificateLoader.cs
src/Microsoft.Identity.Web.Certificate/FromPathCertificateLoader.cs
src/Microsoft.Identity.Web.Certificate/KeyVaultCertificateLoader.cs
tests/E2E Tests/TokenAcquirerTests/CertificateRotationTest.cs
tests/Microsoft.Identity.Web.Test/Certificates/CertificateDescriptionTests.cs
tests/Microsoft.Identity.Web.Test/MsAuth10AtPopTests.cs
tests/Microsoft.Identity.Web.Test/Resource/JwtBearerEventsClaimsValidationTests.cs

Treat warnings as errors.
SYSLIB0057 is using overloads that don't have direct equivalents.

Treat warnings as errors

---

build/template-publish-and-cleanup.yaml

since these changes cause errors in the pipeline it was decided to roll them back temporarily

Revert: Warning Quality Check Build Task

---

.github/workflows/codeql-analysis.yml
.github/workflows/dotnetcore.yml

Update code coverage report to include only `src` files and re-add comments to the workflow see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2983
#3177

use only src files and re-add comments

---

src/Microsoft.Identity.Web.OWIN/AppBuilderExtension.cs
src/Microsoft.Identity.Web.OWIN/Microsoft.Identity.Web.OWIN.xml
src/Microsoft.Identity.Web.OWIN/OwinTokenAcquirerFactory.cs
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/App_Start/Startup.Auth.cs
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config

This pull request addresses several improvements and bug fixes for the Microsoft.Identity.Web.OWIN package, specifically:
1. Fixes a null reference exception in `OwinTokenAcquirerFactory` (#3181)
2. Removes the need to provide the MSAL redirect URI in web applications.
3. Updates the binding redirect in the OWIN samples.
#3181

- Fixes 3181

---

tests/E2E Tests/WebAppUiTests/B2CWebAppCallsWebApiLocally.cs
tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs
tests/E2E Tests/WebAppUiTests/UiTestHelpers.cs
tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs

Added optional retry logic for the test failures related to the client process start failures.
Addresses #3179

Add retry logic to stabilize flaky UI tests

---

tests/E2E Tests/WebAppUiTests/B2CWebAppCallsWebApiLocally.cs
tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs
tests/E2E Tests/WebAppUiTests/UiTestHelpers.cs
tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs

Issue 1: The persistent flakiness 🥐 
After enabling output and error logs, we see [this ](https://identitydivision.visualstudio.com/DevEx/_build/results?buildId=1411321&view=logs&j=f3712adf-8b8e-52fd-13d9-df53740e9087&t=80606c5c-301e-53cc-a2ac-c3815e4eca23&l=833)in a build with failing E2E tests.
We can't replicate this locally as we have the certs configured locally. Moving to HTTP from HTTPS should resolve this for our builds.
Issue 2: Build Hanging
Adding logging from the output/error streams on the processes mean that we need to close them. 🤦‍♀️ Interestingly, the IdWeb build didn't fail on this, but the Unified build did.

Fix E2E tests persistent flakiness + build hanging

---

tests/E2E Tests/WebAppUiTests/B2CWebAppCallsWebApiLocally.cs
tests/E2E Tests/WebAppUiTests/UiTestHelpers.cs

Removes the call to "await currentProcess.WaitForExitAsync();" as the web APIs never terminate by themselves (they are a loop
that serves requests until the process is killed).

Revert WaitForProcess in UI Tests

---

Directory.Build.props
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs

- [] You've read the [Contributor Guide](https://github.com/AzureAD/microsoft-identity-web/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/AzureAD/microsoft-identity-web/blob/master/CODE_OF_CONDUCT.md).
- [] You've included unit or integration tests for your change, where applicable.
This pull request includes updates to dependency versions and modifications to the `TokenAcquisition` class methods in the `Microsoft.Identity.Web.TokenAcquisition` project. The most important changes are as follows:
Dependency updates:
* [`Directory.Build.props`](diffhunk://#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eL85-R85): Updated `MicrosoftIdentityClientVersion` from `4.66.2` to `4.67.1`.
Method modifications:
* …

Update to use MSAL 4.67.1

---

Directory.Build.props

This pull request includes a minor update to the `Directory.Build.props` file. The change updates the version of the `MicrosoftIdentityClientVersion` dependency.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5081 
Dependency version update:
* [`Directory.Build.props`](diffhunk://#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eL85-R85): Updated `MicrosoftIdentityClientVersion` from `4.67.1` to `4.67.2`.
{Detail}

Update to use MSAL 4.67.2

---

src/Microsoft.Identity.Web.OWIN/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.OWIN/OpenIdConnectCachingSecurityTokenProvider.cs

Fixes #3078
See #3124 and #3118 for more context.
The lock isn't needed if the update is done to the config object itself, since it is a reference type, it will be an atomic update. This removes the need to keep two separate fields in sync.

Remove explicit locking in OpenIdConnectCachingSecurityTokenProvider

---

Directory.Build.props
benchmark/Directory.Build.props
tests/DevApps/Directory.Build.props
tests/DevApps/aspnet-mvc/Directory.Build.props
tests/Directory.Build.props
tools/CrossPlatformValidator/CrossPlatformValidation/Directory.Build.props
tools/Directory.Build.props
tools/app-provisioning-tool/Directory.Build.props

Passing on https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1417266&view=results
I had to add suppressions to additional dir.build.props files as the setting is not propagating from the top level .props.

Suppress TFM Build Warnings

---

Directory.Build.props
src/Microsoft.Identity.Web.Certificate/CertificateDescription.cs
tests/Microsoft.Identity.Web.Test/Certificates/CertificateDescriptionTests.cs
tests/Microsoft.Identity.Web.Test/Certificates/DefaultCertificateLoaderTests.cs

- Adopts Abstractions 8.0, which removes the public properties Container and ValueOrReference on CredentialDescriptions, that were for compatibility with IdWeb 1.x
- Clean-up the tests that were using these properties instead of using the right properties. Some of these were using theories for one case
Fixes #3212

Fixing 3212 and cleaning-up technical debt

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAddInTests.cs

#3207 
Pass the assertion/ merged options to MSAL for the ROPC flow and make sure if forceRefresh is set the silent flow is skipped
- Update the TokenAcquisition.cs to pass the ExtraQueryParams, ExtraHttpHeaders etc to MSAL from the mergedOptions and tokenAcquisitionOptions.
- Skip the silent call in case forceRefresh is set to true
Fixes #3207  (in this specific format)

Pass the assertion options to MSAL for ROPC call

---

build/template-restore-build-MSIdentityWeb.yaml

This pull request includes a change to the `build/template-restore-build-MSIdentityWeb.yaml` file. The most important change involves removing a script step that was used to install wasm-tools.
* Removed script step for installing wasm-tools in `build/template-restore-build-MSIdentityWeb.yaml`.
Fixes https://github.com/AzureAD/microsoft-identity-web/issues/3260

Remove step for installing wasm-tools in the build

---

build/template-restore-build-MSIdentityWeb.yaml

**Fix -** 
- The updated script checked if nuget.config exists before using it.
- If it was missing, it used the global NuGet config instead.
This pull request includes changes to the `build/template-restore-build-MSIdentityWeb.yaml` file to improve the handling of NuGet sources in the build process. The key changes focus on adding checks for the existence of a `nuget.config` file, enhancing logging, and ensuring robust handling of NuGet source addition and removal.
Improvements to NuGet source handling:
* Added a check for the existence of `nuget.config` and appropriate logging messages to inform whether the file was found or not.
* Enhanced logging to list existing NuGet sources before making any changes, and to confirm the successful addition or removal of NuGet sources.
* Implemented …

Fix for Remove NuGet Source steps (now with enhanced logging)

---

tests/DevApps/blazor/BlazorApp/Components/Pages/Weather.razor

This pull request includes changes to the `Weather.razor` component in the Blazor application to handle potential null values and initialize arrays properly.
Improvements and code safety enhancements:
* [`tests/DevApps/blazor/BlazorApp/Components/Pages/Weather.razor`](diffhunk://#diff-58ceb5c06c54f7e79b6bb515ae433344bc88de5721583b0e11cf787ca36cd0d5L42-R42): Modified the user identity display to use null-conditional operators to prevent potential null reference exceptions.
* [`tests/DevApps/blazor/BlazorApp/Components/Pages/Weather.razor`](diffhunk://#diff-58ceb5c06c54f7e79b6bb515ae433344bc88de5721583b0e11cf787ca36cd0d5L67-R67): Initialized the `forecasts` array to an empty array using `Array.Empty<WeatherForecast>()` to avoid null-related issues.
Fixes …

Fix CS8602 Warnings in Weather.razor (BlazorApp) – Handle Nullable forecasts and user.Identity

---

src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs
tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/DownstreamApiTests.cs

This PR introduces a change to the way authorization headers are added to HTTP requests, specifically to support SAML tokens. The change ensures that custom SAML authorization schemes are correctly added using TryAddWithoutValidation. This approach allows for more flexible handling of SAML tokens, even when they might not pass standard validation.
Changes:
Replaced the below line to improve compatibility with custom SAML authorization schemes.
```csharp 
httpRequestMessage.Headers.Add(Authorization, authorizationHeader);
``` 
with 
```csharp
httpRequestMessage.Headers.TryAddWithoutValidation(Authorization, authorizationHeader);
```
Added unit tests to validate the new behavior and ensure headers are correctly added in various scenarios.
Fixes …

Add Support for Custom Saml Bearer in HttpRequest Headers

---

.github/workflows/dotnetcore.yml
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirerFactory.cs
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config
tests/E2E Tests/CustomSignedAssertionProviderTests/CustomSignedAssertionProviderExtensibilityTests.cs
tests/E2E Tests/CustomSignedAssertionProviderTests/CustomSignedAssertionProviderTests.csproj
tests/E2E Tests/TokenAcquirerTests/CertificateRotationTest.cs
tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
tests/Microsoft.Identity.Web.Test.Common/Microsoft.Identity.Web.Test.Common.csproj
tests/Microsoft.Identity.Web.Test.Common/TokenAcquirerFactorySingletonProtection.cs
tests/Microsoft.Identity.Web.Test/BaseAuthorizationHeaderProviderTest.cs
tests/Microsoft.Identity.Web.Test/TestTokenAcquisitionHost.cs
tests/Microsoft.Identity.Web.Test/TokenAcquirerFactoryTests.cs

As demonstrated by the unit tests in this PR failing when the locks (also added here) are removed, it is possible in the currently released version to get multiple threads of execution through the `TokenAcquirerFactory.GetDefaultInstance` and `TokenAcquirerFactory.Build` methods when called concurrently. 
These methods perform setup of services critical to the library's functionality so protecting them from concurrent access is essential to avoiding unexpected behavior.
Additionally, due to the static, singleton nature of GetDefaultInstance this PR adds all test classes using the method to a collection to prevent them from being run in parallel.

Locking Down the TokenAcquirerFactory

---

src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs
tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs

This pull request changes logic in the `ParseAuthorityIfNecessary` method in the `MergedOptions` class to fix a bug where the check on the `indexTenant` always evaluates to true.
Originally, there had been a bug here because the '/' chars in the scheme prefix of the URI were not taken into account leading to false positives when checking for the presence of the instance/tenantId
[This PR](https://github.com/AzureAD/microsoft-identity-web/commit/0fdfc96216cb6828f462b85bca21842fc9664915) went into Id Web in 3.1.0 and attempted to address the above bug but accidentally created another where the `indexTenant` >=0 condition always evaluated to true as its min possible value was 7.
The current PR fixes this by making the starting index of the authority URI scheme-agnostic and uses that dynamic …

Fix authority parsing logic

---

changelog.md

Update changelog.md for Id.web 3.8.0

---

tests/E2E Tests/TokenAcquirerTests/CertificateRotationTest.cs
tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs

Fixing TokenAcquireTest (missing reset TokenAcquirerFactory)

---

CodeQL.yaml

Updates CodeQL.yaml to exclude test files

---

Directory.Build.props
src/Microsoft.Identity.Web.TokenCache/CacheSerializerHints.cs
src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs
src/Microsoft.Identity.Web.TokenCache/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenCache/MsalAbstractTokenCacheProvider.cs
src/Microsoft.Identity.Web.TokenCache/TokenCacheErrorMessage.cs
tests/Microsoft.Identity.Web.Test.Common/TestHelpers/TestMsalDistributedTokenCacheAdapter.cs
tests/Microsoft.Identity.Web.Test/L1L2CacheTests.cs

This PR depends on [this MSAL PR](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5175) and should not be merged until this PR is released.
IdWeb will throw an exception if MSAL `TokenCacheNotificationArgs` indicates that it should not configure the distributed cache and it is configured.
[Issue 3304](https://github.com/AzureAD/microsoft-identity-web/issues/3304)

Enabling IdWeb to throw an exception if MSAL indicates that it should not configure the distributed cache

---

src/Microsoft.Identity.Web.TokenAcquisition/Constants.cs
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net462/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net472/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net6.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net7.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net8.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/netstandard2.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs

TokenAcquistion.cs adds its service provider to the acquisition options.
Fixes #3315

Acquisition Extension can resolve dependencies from a service provider

---

src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs
tests/Microsoft.Identity.Web.Test/MergedOptionsTests.cs

Check for null in PrepareAuthorityInstanceForMsal
Fixes #3337

Check for null in PrepareAuthorityInstanceForMsal

---

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
tests/E2E Tests/OidcIdPSignedAssertionProviderTests/OidCIdPSignedAssertionProviderExtensibilityTests.cs
tests/E2E Tests/OidcIdPSignedAssertionProviderTests/appsettings.json

* Confirmed that **client capabilities are already forwarded** by `UpdateConfidentialClientApplicationOptionsFromMergedOptions`, which calls `WithClientCapabilities(...)` when the CCA is built.  
*Tokens issued today already include the expected `xms_cc` claim.*
* Added a comment to `[TokenAcquisition.cs](https://github.com/AzureAD/microsoft-identity-web/compare/gladjohn/cca_capability_idweb?expand=1#diff-3600735102cf2582ea4dc8277f799690b8a8135f4971e0be919fbecd053ae2ca)` to clarify that 
**Added test coverage**
* `CrossCloudFicIntegrationTest_WithCp1` – decodes the JWT and asserts `cp1` is present in the `xms_cc` claim.  
* `CrossCloudFicUnitTest_WithCp1` – inspects the outbound form data and verifies the `claims` payload carries `cp1`.
No functional change; behavior is now safeguarded by …

Add tests to guard client-capabilities forwarding

---

src/Microsoft.Identity.Web/Policy/RequiredScopeOrAppPermissionExtensions.cs
tests/Microsoft.Identity.Web.Test/Resource/RequiredScopeOrAppPermissionExtensionsTests.cs

Updates the `RequiredScopeOrAppPermissionMetadata` class to implement `IAuthRequiredScopeOrAppPermissionMetadata` rather than `IAuthRequiredScopeMetadata`. This makes it conform to the type that the `ScopeOrAppPermissionAuthorizationHandler` looks for in order to determine what scopes and app permissions to check for.
Also added a new unit test file that tests the extension method by creating an endpoint with the appropriate metadata. This test fails when you swap back to `IAuthRequiredScope`.
Fixes #3323

Implement correct metadata interface for `RequiredScopeOrAppPermission` extension method

---

.github/workflows/aot-check.yml
Directory.Build.props
NuGet.Config
build/test-aot.ps1
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.HttpMethods.cs
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.HttpMethods.tt
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs
src/Microsoft.Identity.Web.DownstreamApi/DownstreamApiExtensions.cs
src/Microsoft.Identity.Web.DownstreamApi/Microsoft.Identity.Web.DownstreamApi.csproj
src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj
src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj
src/Microsoft.Identity.Web.TokenAcquisition/ClientInfo.cs
src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net6.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net7.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net8.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/PublicAPI/net9.0/InternalAPI.Unshipped.txt
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirerFactory.cs
src/Microsoft.Identity.Web.TokenAcquisition/WebApiBuilders.cs
tests/DevApps/aspnet-mvc/OwinWebApi/Web.config
tests/DevApps/aspnet-mvc/OwinWebApp/Web.config
tests/Microsoft.Identity.Web.AotCompatibility.TestApp/Microsoft.Identity.Web.AotCompatibility.TestApp.csproj

Fix AoT warnings blocking May release

Fix AoT warnings

---

Directory.Build.props

This is needed as MSAL has a new extensiblity point needed for attributes
See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5389

Bump to MSAL 4.76

---

src/Microsoft.Identity.Web.AgentIdentities/AgentUserIdentityMsalAddIn.cs
src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
tests/E2E Tests/AgentApplications/AgentUserIdentityTestscs.cs

Enable developers of agent apps to override the tenant Id.
Fixes #3461

Support multi-tenant agent user identities

---

Microsoft.Identity.Web.sln
src/Microsoft.Identity.Web.Sidecar/Microsoft.Identity.Web.Sidecar.csproj
src/Microsoft.Identity.Web.Sidecar/Program.cs
tests/E2E Tests/Sidecar.Tests/Sidecar.Tests.csproj
tests/E2E Tests/Sidecar.Tests/ValidateEndpointTests.cs

Adding E2E test

---

src/Microsoft.Identity.Web.Sidecar/Endpoints/AuthorizationHeaderEndpoint.cs
src/Microsoft.Identity.Web.Sidecar/Program.cs
src/Microsoft.Identity.Web.Sidecar/appsettings.json
tests/E2E Tests/Sidecar.Tests/EndpointE2ETests.cs

Add more e2e agent tests for the sidecar project

Add more e2e tests
