AzureAD/microsoft-identity-web

.github/workflows/dotnetcore.yml
This adds a CI build which builds the solution and runs the unit tests
This build runs using **Git actions**, which enables customers and partners to see the result of the build.
Addresses #23
=> Create a CI build using GitHub actions

src/Microsoft.Identity.Web/Resource/IJwtBearerMiddlewareDiagnostics.cs, src/Microsoft.Identity.Web/Resource/IOpenIdConnectMiddlewareDiagnostics.cs, src/Microsoft.Identity.Web/Resource/JwtBearerMiddlewareDiagnostics.cs, src/Microsoft.Identity.Web/Resource/OpenIdConnectMiddlewareDiagnostics.cs, src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs, src/Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs, src/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs
https://github.com/AzureAD/microsoft-identity-web/issues/3
=> implement ILogger<>

build/template-pack-and-sign-all-nugets.yaml
Proposal to solve https://github.com/AzureAD/microsoft-identity-web/issues/45
=> Adds binskim to release build

tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs, tests/Microsoft.Identity.Web.Test/AuthorityHelpersTests.cs, tests/Microsoft.Identity.Web.Test/AzureADB2COpenIDConnectEventHandlersTests.cs, tests/Microsoft.Identity.Web.Test/Base64UrlHelpersTests.cs, tests/Microsoft.Identity.Web.Test/ClaimsPrincipalExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/ClaimsPrincipalFactoryTests.cs, tests/Microsoft.Identity.Web.Test/ClientInfoTests.cs, tests/Microsoft.Identity.Web.Test/CookiePolicyOptionsExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/ExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/MicrosoftIdentityOptionsTests.cs, tests/Microsoft.Identity.Web.Test/Resource/AadIssuerValidatorTests.cs, tests/Microsoft.Identity.Web.Test/Resource/OpenIdConnectMiddlewareDiagnosticsTests.cs
Added unit tests for
- AzureADB2COpenIDConnectEventHandlersTests
- CookiePolicyOptionsExtensionsTests
Cleaned up some tests by using InlineData and changing some local variables to instance.
=> Added new unit tests, cleaned up older ones

src/Microsoft.Identity.Web/ITokenAcquisition.cs, src/Microsoft.Identity.Web/ITokenAcquisitionInternal.cs, src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
rename to GetATForAppAsync
#77
=> move some ITokenAcquisition methods to internal interface

src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs
add overrides with delegates
#84 
@pmaytak after updating samples, decided to address the suggestion you had earlier this week and just do it now. makes the api much simpler.
=> fix xml comments

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
would like to update to 4.11 before we release as next msal release is in 3 weeks.
=> update to msal 4.11

src/Microsoft.Identity.Web/ClaimConstants.cs, tests/B2CWebAppCallsWebApi/TodoListService/AuthorizationPolicies/ScopesRequirement.cs
=> make claimConstant class public

src/Microsoft.Identity.Web/AuthorityHelpers.cs, src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
- move v2 check to authority helper
- fix name
=> address peter's pr comments

tests/B2CWebAppCallsWebApi/WebApp-Calls-WebAPI-B2C.sln, tests/WebAppCallsWebApiCallsGraph/WebApp-Calls-WebAPI-MyOrg.sln
Fixing the VS solutions broken by https://github.com/AzureAD/microsoft-identity-web/commit/1b1a765dfa89c10edc15b8ab02a3d2c4a6dfca40
=> Fixing the VS solutions

Microsoft.Identity.Web.sln, ProjectTemplates/AspNetCoreMicrosoftIdentityWebProjectTemplates.csproj, ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json, ProjectTemplates/templates/StarterWeb-CSharp/Company.WebApplication1.csproj, ProjectTemplates/templates/StarterWeb-CSharp/Startup.cs, ProjectTemplates/templates/StarterWeb-CSharp/Views/Shared/_LoginPartial.OrgAuth.cshtml, ProjectTemplates/templates/WebApi-CSharp/Company.WebApplication1.csproj
- added references to Microsoft.Identity.Web.UI in the **Startup.cs** (using Microsoft.Identity.Web.UI and call to AddMicrosoftIdentityUI())
- added package reference to  Microsoft.Identity.Web.UI in the web app project
- changed the metadata of the template (mvc2) to mention Microsof identity platform and explicit Microsoft.Identity.Web
Fixing the Web API (reference to Microsoft.Identity.Web)
Renaming the generated NuGet package for the templates so that it starts with Microsoft.Identity.Web (Microsoft.Identity.Web.ProjectTemplates)
=> Fixing the Web app template:

src/Microsoft.Identity.Web/MsalAspNetCoreHttpClientFactory.cs, src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tests/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json
=> leverage msal.net's httpclient factory

ProjectTemplates/templates/RazorPagesWeb-CSharp/Pages/Shared/_LoginPartial.OrgAuth.cshtml, ProjectTemplates/templates/RazorPagesWeb-CSharp/Startup.cs, ProjectTemplates/templates/StarterWeb-CSharp/Views/Shared/_LoginPartial.OrgAuth.cshtml
To test, generate and install the templates
and then:
1. Create the app:
```Shell
mkdir b2cwebapp
dotnet new webapp2 --auth IndividualB2C --aad-b2c-instance "https://fabrikamb2c.b2clogin.com" --client-id "90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6" --domain "fabrikamb2c.onmicrosoft.com" --susi-policy-id "b2c_1_susi" --reset-password-policy-id "b2c_1_reset" --edit-profile-policy-id "b2c_1_edit_profile"  
```
2. In the `launchSettings.json`, change the sslPort to 44316
3. Run the app
```Shell
dotnet run
```
4. Navigate to https://localhost:44316
1. Create the app
```Shell
mkdir b2cmvc
dotnet new mvc2 --auth IndividualB2C --aad-b2c-instance "https://fabrikamb2c.b2clogin.com" --client-id "90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6" --domain "fabrikamb2c.onmicrosoft.com" --susi-policy-id "b2c_1_susi" …
```
=> Fixes Web app templates with B2C

src/Microsoft.Identity.Web/AuthorityHelpers.cs, src/Microsoft.Identity.Web/MicrosoftIdentityOptionsValidation.cs, src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tests/Microsoft.Identity.Web.Test/AuthorityHelpersTests.cs, tests/Microsoft.Identity.Web.Test/MicrosoftIdentityOptionsTests.cs
- added unit tests
- fix for null ref w/no client secret
Taking @jmprieur 's suggestions. thank you. much better.
@bgavrilMS - if you want to take a quick look. IDK what to do w/ADFS. ignoring for now.
=> taking JM"s suggestion of checking the options in a separate class

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
Tested the 2 dev samples (web app calls web api and b2c web app/web api)
=> update to msal 4.13

changelog.txt
@jmprieur can you please review the [milestone](https://github.com/AzureAD/microsoft-identity-web/milestone/3)? and ignore the branch name...i thought we were on 0.1.3
=> changelog 0.1.2

src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
fix for https://github.com/AzureAD/microsoft-identity-web/issues/115, and taking in a custom redirect uri and post logout redirect uri.
=> fix postLogout redirectUri

src/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs, tests/B2CWebAppCallsWebApi/Client/Startup.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs, tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs
=> handle no scopes

changelog.txt
https://github.com/AzureAD/microsoft-identity-web/milestone/5
=> changelog 0.1.3-preview

ProjectTemplates/AspNetCoreMicrosoftIdentityWebProjectTemplates.csproj, ProjectTemplates/templates/RazorPagesWeb-CSharp/Company.WebApplication1.csproj, ProjectTemplates/templates/StarterWeb-CSharp/Company.WebApplication1.csproj, ProjectTemplates/templates/WebApi-CSharp/Company.WebApplication1.csproj
=> Updating the template

src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs
Fallback to scp claim name on `VerifyUserHasAnyAcceptedScope()`
=> Fallback to scp claim name

src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs, tests/WebAppCallsMicrosoftGraph/Startup.cs
@jmprieur please review when you have time. doing it in smaller steps.
=> AddMicrosoftWebAppCallsApi naming changes

src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebApiServiceCollectionExtensions.cs, src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppServiceCollectionExtensions.cs, src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebApiCallsWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs, tests/B2CWebAppCallsWebApi/Client/Startup.cs, tests/B2CWebAppCallsWebApi/TodoListService/Startup.cs, tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs, tests/WebAppCallsMicrosoftGraph/Startup.cs, tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs
@jmprieur i think i'm close to the final changes needed. will need you to review carefully. i'll do the same tomorrow.
=> more changes to api surface

tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
- result of merging the api changes branch into master
=> fix build warnings

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
Tested the dev samples.
@jmprieur B2C sample works fine for me, not sure what's up w/yours :(
=> update to latest MSAL

src/Microsoft.Identity.Web/TokenAcquisition.cs
=> use set instead of add for dictionary in tokenAcquisition

src/Microsoft.Identity.Web/ITokenAcquisitionInternal.cs, src/Microsoft.Identity.Web/ServiceCollectionExtensions.cs, src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
=> Changed the DI pattern for Token Acquisition interfaces.

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
=> do not call build service provider

src/Microsoft.Identity.Web/TokenAcquisition.cs
=> remove handleCodeRedemption() as it's listed twice

src/Microsoft.Identity.Web/MicrosoftIdentityOptions.cs, src/Microsoft.Identity.Web/WebApiCallsWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs
=> finish removing singleton work

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebApiCallsWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
=> remove odd pattern for newing up redundant copies of options

src/Microsoft.Identity.Web/Resource/RegisterValidAudience.cs, src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs
This is a new attempt to fix #211 
This time by delegating to Wilson once the default value is set according to the token version
=> New proposal to fix #211

src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
Fixing the outcome of the merge conflict
=> Fix the merge conflict

ProjectTemplates/templates/RazorPagesWeb-CSharp/Startup.cs, ProjectTemplates/templates/StarterWeb-CSharp/Startup.cs, ProjectTemplates/templates/WebApi-CSharp/Startup.cs
Updating the project templates to use the new API in 0.2.0
Fixes #236
=> Updating the project templates with the new verbs

src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs
=> Cloning TokenValidationParameters before use.

src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebApiCallsWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppCallsWebApiAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
Refactored and removed unused code in web app and API extension methods.
=> Extension methods related refactorings.

ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/dotnetcli.host.json, ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/template.json, ProjectTemplates/templates/RazorPagesWeb-CSharp/Company.WebApplication1.csproj, ProjectTemplates/templates/RazorPagesWeb-CSharp/Pages/Index.cshtml.cs, ProjectTemplates/templates/RazorPagesWeb-CSharp/Services/MicrosoftGraphServiceExtensions.cs, ProjectTemplates/templates/RazorPagesWeb-CSharp/Services/TokenAcquisitionCredentialProvider.cs, ProjectTemplates/templates/RazorPagesWeb-CSharp/Startup.cs, ProjectTemplates/templates/RazorPagesWeb-CSharp/appsettings.json, ProjectTemplates/test-templates.bat
=> Add the direct support for Microsoft graph in the templates

README.md
This PR clarifies the expected GA timeframe for those of us who are not in the United States or in the northern hemisphere :)
=> Use geographically neutral timeframe for expected GA

src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebApiServiceCollectionExtensions.cs, src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppServiceCollectionExtensions.cs
Improves the migration aid by adding more actionable recommendations.
As I was updating the Web API incremental tutorial, I thought we could provider more actionable recommendations to upgrade, so I've tweaked the obsolete messages with this goal
=> Improves the migration aid

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
@bgavrilMS once the build finishes, this should work w/the cache key.
=> update to msal 4.16.1

src/Microsoft.Identity.Web/TokenCacheProviders/Session/SessionTokenCacheProviderExtension.cs
=> Add ISession provider.

changelog.txt
@jennyf19 Can you please suggest a summary for #27, #20, #295? I wasn't sure how to phrase them correctly.
Also since we added optional parameters to methods in `TokenAcquisition`, that makes it a runtime breaking change, right? Should I add it to the breaking changes section?
=> 0.2.1-preview changelog

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
tested w/the dev samples + b2c.
=> update to msal 4.17.0

ProjectTemplates/templates/BlazorServerWeb-CSharp/Properties/launchSettings.json, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/.template.config/template.json, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Client/Properties/launchSettings.json, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Properties/launchSettings.json, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Startup.cs, ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/template.json, ProjectTemplates/templates/RazorPagesWeb-CSharp/Pages/Index.cshtml, ProjectTemplates/templates/RazorPagesWeb-CSharp/Properties/launchSettings.json, ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json, ProjectTemplates/templates/StarterWeb-CSharp/Properties/launchSettings.json, ProjectTemplates/templates/StarterWeb-CSharp/Views/Home/Index.cshtml, ProjectTemplates/templates/WebApi-CSharp/.template.config/template.json, ProjectTemplates/templates/WebApi-CSharp/Properties/launchSettings.json, ProjectTemplates/templates/WebApi-CSharp/Startup.cs, src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.xml, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, tests/BlazorServerCallsGraph/Properties/serviceDependencies.json, tests/BlazorServerCallsGraph/Properties/serviceDependencies.local.json, tests/BlazorServerCallsGraph/blazor.csproj, tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
+ removing an MSAL ref on test infra
=> Updating the templates from ASP.NET Core

src/Microsoft.Identity.Web/TokenAcquisition.cs, tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/TodoListController.cs, tests/WebAppCallsWebApiCallsGraph/TodoListService/Startup.cs, tests/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json
=> fix for propagating the tenant information

tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/TodoListController.cs
Fixes https://identitydivision.visualstudio.com/IDDP/_workitems/edit/1097354
=> Fixes Azure DevOps issue 1097354

src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs, tests/Microsoft.Identity.Web.Test/Resource/ScopesRequiredHttpContextExtensionsTests.cs
=> throw if scopes are not valid

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
Tested the OBO scenario (with Adele)
=> Update to MSAL 4.17.1

src/Microsoft.Identity.Web/Constants/IDWebErrorMessage.cs, src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs
fix for #392 
cc: @DanielMannInCycle @javiercn
=> fix blazor null httpcontext when using Azure SignalR

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
Tested with the projects in tests folder. 
Tested with a few templates..
Issue #414
=> Update JwtBearer, OpenIdConnect dependencies  to 5.0.0-*.

src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs
=> handle the null navigationManager w/blazor apps during pre-rendering

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiServiceCollectionExtensions.cs
=> return correct builder

ProjectTemplates/templates/BlazorServerWeb-CSharp/Services/DownstreamWebApi.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiExtensions.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/MicrosoftGraph/MicrosoftGraphExtensions.cs, tests/BlazorServerCallsGraph/Startup.cs, tests/WebAppCallsMicrosoftGraph/Startup.cs, tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs
=> rename MicrosoftGraph* to just MicrosoftGraph

.github/workflows/codeql-analysis.yml, Microsoft.Identity.Web-Source.sln
Add CodeQL analysis (codeql-analysis.yml) and separate solution file for only source projects.
=> Add CodeQL analysis

ProjectTemplates/configuration.json
=> add policy to the b2c authority string

ProjectTemplates/configuration.json, tools/ConfigureGeneratedApplications/Model/Projects.cs, tools/ConfigureGeneratedApplications/Program.cs
@jmprieur i think these are the final fixes for the tool. i also did a format fix on the regular files (not the templates)
=> final (hopefully) fixes for the tool

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs
Changed AddMicrosoftIdentityWebApiImplementation to
add named configuration options for MicrosoftIdentityOptions.
Changed AddOptions Configure to use IOptionsMonitor to get
and use the named options.
Attempt at fix for #429
=> Fix: API Multiple Identity Providers

CONTRIBUTING.md, README.md, RELEASES.md, SECURITY.md
=> fix link & some md style suggestions

ProjectTemplates/templates/BlazorServerWeb-CSharp/Startup.cs, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Controllers/WeatherForecastController.cs, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Startup.cs, ProjectTemplates/templates/RazorPagesWeb-CSharp/Pages/Index.cshtml.cs, ProjectTemplates/templates/RazorPagesWeb-CSharp/Startup.cs, ProjectTemplates/templates/StarterWeb-CSharp/Controllers/HomeController.cs, ProjectTemplates/templates/StarterWeb-CSharp/Startup.cs, ProjectTemplates/templates/WebApi-CSharp/.template.config/dotnetcli.host.json, ProjectTemplates/templates/WebApi-CSharp/Controllers/WeatherForecastController.cs, ProjectTemplates/templates/WebApi-CSharp/Startup.cs
Adressing PR feedback from John on templates
See https://github.com/dotnet/aspnetcore/pull/25309
=> Adressing PR feedback from John on templates

src/Microsoft.Identity.Web/Constants/IDWebErrorMessage.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs
Taking @NikolaosWakem code snippet in the issue which has improvements in this area. Only todo now is testing.
#503 
cc: @jmprieur
=> Improvements to CallWebApiForUserAsync()

tests/IntegrationTests/IntegrationTestService/IntegrationTestService.csproj, tests/IntegrationTests/WebAppUiTests/WebAppUiTests.csproj
thanks @jmprieur for noticing this.
=> fix strong name issue

src/Microsoft.Identity.Web/Constants/Constants.cs, src/Microsoft.Identity.Web/IdHelper.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/MsalAspNetCoreHttpClientFactory.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
example:
ApplicationId   env_time  sku  version  idweb 
86699d80-dd21-476a-bcd1-7c1a3d471f75    2020-09-12 00:57:18.0331189    MSAL.NetCore    4.18.0.0    IDWeb.0.4.0.0
86699d80-dd21-476a-bcd1-7c1a3d471f75    2020-09-12 00:57:18.2596998    MSAL.NetCore    4.18.0.0    IDWeb.0.4.0.0
86699d80-dd21-476a-bcd1-7c1a3d471f75    2020-09-12 00:57:18.3331756    MSAL.NetCore    4.18.0.0    IDWeb.0.4.0.0
86699d80-dd21-476a-bcd1-7c1a3d471f75    2020-09-12 00:57:29.1763271    MSAL.NetCore    4.18.0.0    IDWeb.0.4.0.0
86699d80-dd21-476a-bcd1-7c1a3d471f75    2020-09-12 00:57:29.1771464    MSAL.NetCore    4.18.0.0    IDWeb.0.4.0.0
86699d80-dd21-476a-bcd1-7c1a3d471f75    2020-09-12 00:58:29.2015480    ID_NETSTANDARD2_0    5.5.0.0    IDWeb.0.4.0.0
86699d80-dd21-476a-bcd1-7c1a3d471f75    2020-09-12 …
=> send sku & version for basic telemetry

src/Microsoft.Identity.Web/TokenAcquisition.cs
will have merge conflicts probably, but thought of moving things around.
=> format fixes in token acquisition

src/Microsoft.Identity.Web/TokenAcquisition.cs, tests/IntegrationTests/IntegrationTestService/Startup.cs
=> take one client secret from options

src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs
fix for #573 and also addressing #404 
FYI: @jmprieur for the singleton vs scoped issue
=> fix blazor loop w/azure signalR service

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
=> update to 4.19

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs, tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs, tests/Microsoft.Identity.Web.Test/Resource/AadIssuerValidatorTests.cs
=> add long form check of tenant id

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
=> fixing options.TokenValidationParameters.Clone()

src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs
=> use request content in CallWebApiForAppAsync

src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs
Ensuring the redirect URI is correct, fixing #626
=> ensure correct redirect links

.github/workflows/dotnetcore.yml, build/template-install-dotnet-core.yaml, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs, tests/PerformanceTests/PerformanceTestService/appsettings.json
Attempt to understand why the build with preview 7 fails on GitHub
=> Attempt to fix the failing test in .NET 5.0

build/template-install-dotnet-core.yaml, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs, tests/PerformanceTests/PerformanceTestService/appsettings.json
=> reenable test

src/Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs, src/Microsoft.Identity.Web/Resource/MicrosoftIdentityIssuerValidatorFactory.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/Resource/AadIssuerValidatorTests.cs, tests/Microsoft.Identity.Web.Test/WebApiExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
=> make aadissuervalidator a singleton

src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj, src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
~~MSAL needs to re-release w/out WAM.~~
TODO: test w/4.20.1 fyi: @jmprieur
=> [do not merge ] update msal, graph, graph beta

ProjectTemplates/test-templates-from-nuget.bat, ProjectTemplates/test-templates.bat, tools/ConfigureGeneratedApplications/ConfigureGeneratedApplications.csproj, tools/ConfigureGeneratedApplications/ConfigureGeneratedApplications.sln, tools/ConfigureGeneratedApplications/Model/Replacement.cs, tools/ConfigureGeneratedApplications/Program.cs
Improving the testing tooling to make it easier to test ASP.NET Core project templates
=> Improving the project template testing tooling 

src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj
=> add strong name to UI

tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/Program.cs, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/TestRunner.cs, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/TestRunnerOptions.cs, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/appsettings.json
Smaller incremental PR related to adding parallelization (#648)
- Adds `TestRunnerOptions` class for config
=> Add options class for config.

src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/TokenAcquisitionOptions.cs
=> add claims to token acquisition options

src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs
also update graph sdk. 
@jmprieur also a public api addition, so you might want to try it.
=> add challengeUser for conditional access processing

src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiGenerics.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/IDownstreamWebApi.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, tests/WebAppCallsWebApiCallsGraph/Client/Controllers/TodoListController.cs
=> Improve public api w/extensions for downstream web api

src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs, src/Microsoft.Identity.Web/Constants/Constants.cs, src/Microsoft.Identity.Web/Constants/IDWebErrorMessage.cs
@jmprieur for time, decided to just make some small edits in a pr. also tested w/the sample, it's pretty nice.
=> small edits to graph pr

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
tested web app/web api dev sample
=> update msal 4.22

tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/Program.cs, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/ScalableTokenCacheHelper.cs, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/TestRunner.cs, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/TestRunnerOptions.cs, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/appsettings.json
Adds parallel tasks that make requests.
In the following PR will aggregate the metrics for all tasks and some cleanup.
#648
Example of output now:
=> Added parallel tasks to perf client

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
tested b2c & web app calls web api & web app calls graph
=> update to msal .net 4.23

src/Microsoft.Identity.Web/Resource/RolesRequiredHttpContextExtensions.cs, src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs
=> fix scope validation error

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationTokenAcquisition.cs
missed this one in the review.
=> fix spelling in comment

src/Microsoft.Identity.Web/Constants/Constants.cs
=> fix login/domain hint constant

src/Microsoft.Identity.Web/TokenAcquisition.cs, tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs
=> take cca options redirecturi if provided

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
=> check for validateIssuer

src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
#809 & #133 need to do more testing, so WIP
=> fix cookie issue

changelog.md
creating as a draft, as we might have one more issue fixed before running the release
=> changelog1.4

src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj
Changed to the latest version of the Microsoft.Graph.Beta package
=> Updating version of Graph package

tests/B2CWebAppCallsWebApi/Client/appsettings.json
edit/profile still works as v2, so just leaving it for now
=> update to v3 user flows for b2c

ProjectTemplates/templates/BlazorServerWeb-CSharp/.template.config/template.json, ProjectTemplates/templates/BlazorServerWeb-CSharp/appsettings.json, ProjectTemplates/templates/RazorPagesWeb-CSharp/.template.config/template.json, ProjectTemplates/templates/RazorPagesWeb-CSharp/appsettings.json, ProjectTemplates/templates/StarterWeb-CSharp/.template.config/template.json, ProjectTemplates/templates/StarterWeb-CSharp/appsettings.json, ProjectTemplates/templates/WebApi-CSharp/.template.config/template.json, ProjectTemplates/templates/WebApi-CSharp/appsettings.json
=> replace loginmicrosoftonline.com w/b2clogin.com

tests/Microsoft.Identity.Web.Test/ExceptionHandlingTest.cs
=> fix test name

ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/appsettings.json, ProjectTemplates/templates/WebApi-CSharp/appsettings.json, ProjectTemplates/templates/Worker-CSharp/appsettings.json
=> fix downstream api spelling in some templates

ProjectTemplates/AspNetCoreMicrosoftIdentityWebProjectTemplates.csproj, ProjectTemplates/templates/Functions-CSharp/Company.FunctionApp1.csproj
- the template csproj was not loading
- appsettings.json was not loading from the tool
=> fix func template issue

ProjectTemplates/templates/Functions-CSharp/SampleFunc.cs
=> fix space that automagically was added

ProjectTemplates/configuration.json
can't base the template on worker2, as it uses different endpoints:
so going to use webapi2 instead.
=> make func2 based on webapi2

ProjectTemplates/templates/Functions-CSharp/appsettings.json
=> add logging in appsettings

ProjectTemplates/configuration.json
@jmprieur the tooling finally works now.
=> fix func tooling

tests/WebAppCallsWebApiCallsGraph/gRPC/grpc.csproj
=> fix gR{C warning

ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Controllers/CallWebApiController.cs, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Controllers/ShowProfileController.cs, ProjectTemplates/templates/ComponentsWebAssembly-CSharp/Server/Controllers/WeatherForecastController.cs, ProjectTemplates/templates/Functions-CSharp/SampleFunc.cs, ProjectTemplates/templates/WebApi-CSharp/Controllers/WeatherForecastController.cs, ProjectTemplates/templates/Worker-CSharp/GreeterService.cs
@jmprieur  let's discuss, i have a few questions.
=> update templates for new scope attribute (initial commit)

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
=> update to msal 4.26

tools/app-provisioning-tool/app-provisioning-lib/AuthenticationParameters/ApiPermission.cs, tools/app-provisioning-tool/app-provisioning-lib/AuthenticationParameters/ApplicationParameters.cs, tools/app-provisioning-tool/app-provisioning-lib/AuthenticationParameters/PlatformType.cs, tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/CodeReader.cs, tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/CodeWriter.cs, tools/app-provisioning-tool/app-provisioning-lib/CodeReaderWriter/ProjectAuthenticationSettings.cs, tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/DeveloperCredentialsReader.cs, tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/IDeveloperCredentialsOptions.cs, tools/app-provisioning-tool/app-provisioning-lib/DeveloperCredentials/MsalTokenCredential.cs, tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs, tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/ResourceAndScope.cs, tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/Spa.cs, tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/TokenCredentialAuthenticationProvider.cs, tools/app-provisioning-tool/app-provisioning-lib/ProjectDescription/MatchesForProjectType.cs, tools/app-provisioning-tool/app-provisioning-lib/ProjectDescription/ProjectDescriptionReader.cs, tools/app-provisioning-tool/app-provisioning-lib/ProjectDescription/PropertyMapping.cs, tools/app-provisioning-tool/app-provisioning-lib/Summary/Change.cs, tools/app-provisioning-tool/app-provisioning-lib/Summary/Summary.cs, tools/app-provisioning-tool/app-provisioning-lib/Tool/AppProvisioningTool.cs, tools/app-provisioning-tool/app-provisioning-lib/Tool/ProvisioningToolOptions.cs, tools/app-provisioning-tool/app-provisioning-tool/Program.cs, tools/app-provisioning-tool/tests/CleanUp.cs, tools/app-provisioning-tool/tests/E2ETests.cs, tools/app-provisioning-tool/tests/UnitTests.cs
- fixing a few more warnings
- adding license info
- spelling fixes
- xml randomness
=> more updates

tools/app-provisioning-tool/app-provisioning-tool/Program.cs
Fixes https://github.com/jmprieur/app-provisonning-tool/issues/23
Under tools\app-provisioning-tool:
```Shell
dotnet tool uninstall --global ms-identity-app
dotnet pack
dotnet tool install --global --add-source app-provisioning-tool\nupkg ms-identity-app
```
```Shell
ms-identity-app --help
```
=> fix for issue 23

tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs, tools/app-provisioning-tool/tests/E2ETests.cs
=> Fixing the end to end test (which were no longer compiled)

changelog.md
@jmprieur  please provide text for the info on the tool. thx.
=> update changelog 1.7

src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs, tests/Microsoft.Identity.Web.Test/TestDistributedCache.cs
=> fix l2 cache refresh

tests/WebAppCallsWebApiCallsGraph/Client/appsettings.json, tests/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/TodoListController.cs, tests/WebAppCallsWebApiCallsGraph/TodoListService/Startup.cs, tests/WebAppCallsWebApiCallsGraph/TodoListService/TodoListService.csproj, tests/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json
=> add l2 cache to dev app web API

src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
@jmprieur I've only tested web app calls web API & web app calls Graph
=> update MSAL & Graph SDKs

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationHandler.cs, src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationInformation.cs, src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationTokenAcquisition.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/TokenAcquisition.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tests/WebAppCallsMicrosoftGraph/Pages/Index.cshtml.cs, tests/WebAppCallsMicrosoftGraph/Properties/launchSettings.json, tests/WebAppCallsMicrosoftGraph/Startup.cs
implement GetAuthenticationResultForUserAsync for EasyAuth
Still need to:
- process the static analysis issues
- test with easy auth
=> Proposal to implement GetAuthenticationResultForUserAsync for EasyAuth

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationHandler.cs, src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationInformation.cs, src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationTokenAcquisition.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiOptions.cs, src/Microsoft.Identity.Web/ITokenAcquisition.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/TokenAcquisitionOptions.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tests/WebAppCallsMicrosoftGraph/Pages/Index.cshtml.cs, tests/WebAppCallsMicrosoftGraph/Properties/launchSettings.json, tests/WebAppCallsMicrosoftGraph/Startup.cs
@jmprieur I didn't know what to do w/easy auth. I'm not familiar enough w/that scenario. we'll need to discuss.
=> [WIP] add pop option to id web 

src/Microsoft.Identity.Web/CertificateManagement/CertificateDescription.cs, src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs, src/Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.Common/Microsoft.Identity.Web.Test.Common.csproj, tests/Microsoft.Identity.Web.Test/Certificates/CertificateDescriptionTests.cs, tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj
@jmprieur i haven't tested manually yet.
=> initial commit...add support for net462

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForUserIntegrationTests.cs, tests/blazorwasm-b2c/blazorwasm2-b2c.csproj, tests/blazorwasm2-b2c-hosted/Client/blazorwasm2-b2c-hosted.Client.csproj, tests/blazorwasm2/Client/blazorwasm2-singleOrg-hosted4.Client.csproj
one more...that didn't work, but i'll run the release build from here to test
=> fix gov issue again

tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForUserIntegrationTests.cs
[1096](https://github.com/AzureAD/microsoft-identity-web/issues/1096)
=> reenable lab tests

src/Microsoft.Identity.Web/IncrementalConsentAndConditionalAccessHelper.cs
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
Unhandled exception in circuit '7i9ZYkxr5M2fSiYjUxqZdAGZ_UL-vADHD_MMYznfhYs'.
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.HashSet`1[System.String]' to type 'System.Collections.Generic.List`1[System.String]'.
=> fix for blazor

tools/app-provisioning-tool/README.md
Add instruction to add provisioning tool to Visual Studio
=> Add instructions to add provisioning tool to Visual Studio

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/WebAppCallsWebApiCallsGraph/TodoListService/TodoListService.csproj
tested w/azure functions and the web app calls web API
=> re-add wilson for just .net 5

README.md
=> fix STO tags

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
#1136 
thanks for the repro @travisneale ...this workaround should resolve the issue until the next middleware release w/the fix is out.
=> workaround for names claim

src/Microsoft.Identity.Web/ITokenAcquisition.cs
=> fix obselete message and make "true" not false.

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
=> revert wilson workaround and use latest 6.10.2

src/Microsoft.Identity.Web/IOptionsForIdentityWeb.cs, src/Microsoft.Identity.Web/MergedOptions.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/MicrosoftIdentityOptionsValidation.cs, src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/MicrosoftIdentityOptionsTests.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs, tests/MultipleAuthSchemes/Startup.cs, tests/MultipleAuthSchemes/appsettings.json, tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs
thought experiment, not done at all.
=> merge options partial idea

.github/ISSUE_TEMPLATE/documentation.md, tools/app-provisioning-tool/README.md
=> fix spelling

src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs, src/Microsoft.Identity.Web/Constants/Constants.cs, src/Microsoft.Identity.Web/Constants/IDWebErrorMessage.cs, src/Microsoft.Identity.Web/TokenAcquisition.Logger.cs, src/Microsoft.Identity.Web/TokenAcquisition.cs
opening so we can review easier...
=> cert rotation

src/Microsoft.Identity.Web/MergedOptions.cs
@jmprieur fix for azure functions when the cca options are not getting populated.
=> fix cca options w/azure functions

src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs, src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.xml, tests/WebAppCallsWebApiCallsGraph/Client/Views/Shared/_LoginPartial.cshtml
=> honor redirect after sign-in

src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Pages/Account/Error.cshtml
=> update error messaging

src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs
=> remove lock in response string

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/WebAppCallsWebApiCallsGraph/TodoListService/TodoListService.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
=> update wilson to latest (6.11.1)

src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs, tests/Microsoft.Identity.Web.Test/Certificates/DefaultCertificateLoaderTests.cs
=> decrypt cert fix

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/TokenAcquisition.cs, src/Microsoft.Identity.Web/TokenAcquisitionOptions.cs, src/Microsoft.Identity.Web/TokenCacheProviders/CacheSerializerHints.cs, src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs, src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs, src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs
=> [wip] add cancellation token support

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
tested B2C & web app calls Graph
=> update to 4.32.1 msal

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
tested web app calls web api and b2c.
=> update msal 4.33

src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj, src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj, src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
symbols package needs to be downloaded as well.
#1308
=> add deterministic build

src/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs
=> update aadissuer for organizations

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs, src/Microsoft.Identity.Web/TokenCacheProviders/TokenCacheExtensions.cs, tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs
Replacing Microsoft.Owin.Security
by Microsoft.AspNetCore.DataProtection
=> Addressing Karel's feedback

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs, src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapterOptions.cs, src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs, src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs, src/Microsoft.Identity.Web/TokenCacheProviders/TokenCacheExtensions.cs, tests/Microsoft.Identity.Web.Test.Common/TestHelpers/MsalTestTokenCacheProvider.cs, tests/Microsoft.Identity.Web.Test.Common/TestHelpers/TestMsalDistributedTokenCacheAdapter.cs, tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs, tests/Microsoft.Identity.Web.Test/L1L2CacheOptionsTests.cs, tests/Microsoft.Identity.Web.Test/L1L2CacheTests.cs, tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj
Fix for https://github.com/AzureAD/microsoft-identity-web/issues/1044
=> provide option to encrypt distributed cache

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
tested b2c & web app calls web api
=> update msal 4.35

src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj, src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj
=> update graph sdk's to latest

src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/Microsoft.Identity.Web.MicrosoftGraph.csproj, src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj
=> test for graph key isssue

src/Microsoft.Identity.Web/MergedOptions.cs
=> fix cookie nonce & correlationCookie issue

src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs, src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapterOptions.cs, tests/Microsoft.Identity.Web.Test/L1L2CacheOptionsTests.cs, tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs, tests/WebAppCallsWebApiCallsGraph/TodoListService/Startup.cs
=> provide option to disable L1 cache

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/WebAppCallsWebApiCallsGraph/TodoListService/TodoListService.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
use a * for wilson minor version 6.*
=> update to Wilson.star

src/Microsoft.Identity.Web/TokenAcquisition.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
=> fix for anonymous controller

src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
=> update to msal 4.36

src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
options.Events was being assigned multiple times, deleted the 2 first
=> fix: Delete multiple options.Events assignment.

src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/Policy/ScopeAuthorizationHandler.cs, src/Microsoft.Identity.Web/Policy/ScopeAuthorizationRequirement.cs
fixing the TSA issues...I think we can throw if the requirement is null, like asp.net core does [here](https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.Authorization/AuthorizationHandlerContext.cs#L31) and i'm not sure how `*.Remove(requirement)` will handle the [null value](https://github.com/aspnet/Security/blob/26d27d871b7992022c082dc207e3d126e1d9d278/src/Microsoft.AspNetCore.Authorization/AuthorizationHandlerContext.cs#L95).
=> fix tsa issues

.github/ISSUE_TEMPLATE/bug_report.md
=> update issue template w/Pii section

src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/WebAppCallsWebApiCallsGraph/gRPC/grpc.csproj
=> update jwtBearer package to 5.0.12-*

src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs
=> fix tenant missing issue

src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApi.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiOptions.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
=> allow customization of headers

src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
ran tests and tested web app calls web API calls graph.
=> update to msal 4.40

src/Microsoft.Identity.Web/Policy/ScopeAuthorizationHandler.cs
Took your suggestion @pealmeid, really appreciate the detailed analysis of the issue, saved me a lot of time.
=> fix for 1600 from @pealmeid

src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj, src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj, src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
Removing the StyleCop.Analyzers beta has it has a dependency named Unstable
=> Remove beta pckage StyleCop.Analyzers

src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationInformation.cs
=> fix settingName for easy auth

src/Microsoft.Identity.Web/TokenAcquisition.cs
=> send tokenAcquisitionOption

src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
tested w/web app calls web api calls graph
=> update to msal4.42

changelog.md
=> changelog 1.23.1

src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppServiceCollectionExtensions.cs
=> fix param name

tests/MultipleAuthSchemes/Controllers/HomeB2CController.cs, tests/MultipleAuthSchemes/Controllers/HomeController.cs, tests/MultipleAuthSchemes/mvcwebapp-graph.csproj
Updates the HomeB2CController to align with changes in the web API that is deployed by the B2c team.
=> Updates the HomeB2CController to align with changes in the

src/Microsoft.Identity.Web/IdentityFederationOptions.cs
@jmprieur sorry, I thought I had pushed this.
=> update xml in identityFederationOptions class

src/Microsoft.Identity.Web.IdentityFederation/Microsoft.Identity.Web.xml, tools/GenerateMergeOptionsMethods/GenerateMergeOptionsMethods.csproj
need to re-lnk the files for the test project
=> re-add linked files

src/Microsoft.Identity.Web/Policy/ScopeAuthorizationHandler.cs
=> fix for 1707

src/Microsoft.Identity.Web/DownstreamWebApiSupport/MicrosoftIdentityAuthenticationMessageHandlerHttpClientBuilderExtensions.cs
=> Use scoped and not singleton for service

src/Microsoft.Identity.Web/LoggingOptions.cs, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml, src/Microsoft.Identity.Web/MicrosoftIdentityBaseAuthenticationBuilder.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/WebAppCallsWebApiCallsGraph/Client/appsettings.json, tests/WebAppCallsWebApiCallsGraph/TodoListService/TodoListService.csproj, tests/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json
=> Implement IIdentityLogger

.github/workflows/codeql-analysis.yml, Microsoft.Identity.Web-Source.sln
Update action versions in CodeQL YAML (previous ones are obsolete and were breaking)
Add other projects to Microsoft.Identity.Web-Source.sln which is used by CodeQL.
Tested to work on this branch
=> Update CodeQL action

build/template-restore-build-MSIdentityWeb.yaml
@jmprieur found [this](https://docs.opensource.microsoft.com/tools/cg/how-to/pull-request-integration/) for early reporting of governance alerts
=> add early governance alerting

Microsoft.Identity.Web.sln, src/Directory.Build.props, src/Microsoft.Identity.Web.OWIN/Microsoft.Identity.Web.OWIN.csproj, src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/Microsoft.Identity.Web.TokenAcquisition.Abstractions.csproj, src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj, tests/aspnet-mvc/OwinWebApp/OwinWebApp.csproj, tests/aspnet-mvc/OwinWebApp/Web.config
tested locally, but might want to pull it yourself as well and check things are building/working as expected.
=> update new dlls with directory.build.props

src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/ApplicationOptions/AuthenticationOptions.cs
#1818 RedirectUri property is not needed
=> add EnablePiiLogging property to AuthenticationOptions

Microsoft.Identity.Web.sln, TokenAcquirerTests/TokenAcquirer.cs, TokenAcquirerTests/TokenAcquirerTests.csproj, TokenAcquirerTests/Usings.cs, src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/ApplicationOptions/CredentialDescription.cs, src/Microsoft.Identity.Web.TokenAcquisition/ConfidentialClientApplicationBuilderExtension.cs, src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs, src/Microsoft.Identity.Web.TokenAcquisition/MicrosoftIdentityOptions.cs, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.Logger.cs, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs, tests/daemon-app/Daemon-app/Program.cs
=> intial commit for using client credentials

src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/GraphServiceCollectionExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProviderOption.cs, src/Microsoft.Identity.Web.TokenAcquisition.Abstractions/DownstreamRestApi/DownstreamRestApiOptions.cs, tests/daemon-app/Daemon-app/Program.cs
=> initial commit for adding downstreamRestApiOptions to Graph

tests/PerformanceTests/GenerateBulkUsers.ps1, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/appsettings.json, tests/PerformanceTests/PerformanceTestService/appsettings.json
contosolob.onmicrosoft.com as the previous one
is no longer accessible to us
Fixing the Powershell script that probably never worked
=> Moving the performance testing to another tenant

src/Microsoft.Identity.Web.MicrosoftGraph/GraphServiceCollectionExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs, src/Microsoft.Identity.Web.TokenAcquisition/ConfidentialClientApplicationBuilderExtension.cs
=> Use IAuthorizationHeaderProvider instead of ITokenAcquisition

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
=> remove logCritical

tests/WebAppCallsWebApiCallsGraph/gRPC/grpc.csproj
=> address cve-2022-1941 for Google.Protobuf

src/Directory.Build.props, src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj, src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
(in Microsoft.Identity.Web.TokenAcquisition.Abstractions NuGet package) Updating MSAL and fixing the support for Pop
=> Leveraging Microsoft.Identity.Abstraction DLL/ns

build/credscan-exclusion.json
ran a [build here](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1006664&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1876155b-e1ef-55fc-d177-9285fc268cbf) no credscan issues.
=> update credscan exclusion file

src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/TokenAcquisitionAspnetCoreHost.cs, src/Microsoft.Identity.Web.TokenAcquisition/ConfidentialClientApplicationBuilderExtension.Logger.cs, src/Microsoft.Identity.Web.TokenAcquisition/ConfidentialClientApplicationBuilderExtension.cs, src/Microsoft.Identity.Web.TokenAcquisition/LogMessages.cs, src/Microsoft.Identity.Web.TokenAcquisition/LoggingEventId.cs, src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.Logger.cs, src/Microsoft.Identity.Web.TokenCache/Distributed/MsalDistributedTokenCacheAdapter.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs
and clean up a few existing log formats
=> using high-perf logging for the newly added log messages

tests/WebAppCallsWebApiCallsGraph/Client/TodoListClient.csproj
=> CVE-2022-1941

src/Directory.Build.props, src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj, src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj, src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
see CVE-2021-26701 for details
=> move back to 4.7.2 for system.text.encodings.web

changelog.md, src/Directory.Build.props, src/Microsoft.Identity.Web.OWIN/OwinTokenAcquisitionHost.cs, src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/JwtBearerOptionsMerger.cs, src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/TokenAcquisitionAspnetCoreHost.cs, src/Microsoft.Identity.Web.TokenAcquisition/DefaultTokenAcquisitionHost.cs, src/Microsoft.Identity.Web.TokenAcquisition/IMergedOptionsStore.cs, src/Microsoft.Identity.Web.TokenAcquisition/MergedOptionsStore.cs, src/Microsoft.Identity.Web.TokenAcquisition/OptionsMergers/ConfidentialClientApplicationOptionsMerger.cs, src/Microsoft.Identity.Web.TokenAcquisition/OptionsMergers/MicrosoftAuthenticationOptionsMerger.cs, src/Microsoft.Identity.Web.TokenAcquisition/OptionsMergers/MicrosoftIdentityOptionsMerger.cs, src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirerFactory-GetTokenAcquirers.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tests/Microsoft.Identity.Web.Test/MicrosoftIdentityOptionsTests.cs, tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs, tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs
Replace IOptionsMonitor<MergedOptions> by
IMergedOptionsStore.
See also https://github.com/AzureAD/microsoft-identity-web/pull/1979 for master (v1.0) (this PR is for rel/v2.0)
=> Fix for #1957

Directory.Build.props
=> update to abstractions 1.1.0

Directory.Build.props, src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj, src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj, src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/DevApps/AzureFunctions/SampleFunc/SampleFunc.csproj, tests/DevApps/blazorserver-calls-api/Service/ToDoListService.csproj, tests/DevApps/blazorserver-calls-api/ToDoListModel/ToDoListModel.csproj, tests/DevApps/blazorwasm2-b2c-hosted/Shared/blazorwasm2-b2c-hosted.Shared.csproj, tests/DevApps/blazorwasm2/Shared/blazorwasm2-singleOrg-hosted4.Shared.csproj, tests/DevApps/daemon-app/Daemon-app/Daemon-app.csproj, tools/ConfigureGeneratedApplications/ConfigureGeneratedApplications.csproj
=> re-add netcoreapp3.1 target fwk

Microsoft.Identity.Web.sln, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirerFactory.cs, tests/DevApps/Directory.Build.props, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/DaemonConsoleCallingDownstreamApi.csproj, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/Program.cs, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/appsettings.json, tests/DevApps/daemon-app/daemon-console-calling-msgraph/DaemonConsoleCallingMsGraph.csproj, tests/DevApps/daemon-app/daemon-console-calling-msgraph/Program.cs, tests/DevApps/daemon-app/daemon-console-calling-msgraph/appsettings.json, tests/DevApps/daemon-app/minimal-web-api/Controllers/WeatherForecastController.cs, tests/DevApps/daemon-app/minimal-web-api/MinimalWebApi.csproj, tests/DevApps/daemon-app/minimal-web-api/Program.cs, tests/DevApps/daemon-app/minimal-web-api/Properties/launchSettings.json, tests/DevApps/daemon-app/minimal-web-api/WeatherForecast.cs, tests/DevApps/daemon-app/minimal-web-api/appsettings.Development.json, tests/DevApps/daemon-app/minimal-web-api/appsettings.json
Adding minimal daemon samples:
- daemon app calling msgraph
- daemon app calling downstream web API
=> Adding minimal samples (for the doc)

build/Microsoft.Identity.Web-Source-Assemblies.dgml
=> Update dependency diagram (renamed DownstremRestApi.dll to DownstreamApi.dll)

src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/TokenAcquisition-AspnetCore.cs, src/Microsoft.Identity.Web.TokenAcquisition/AuthCodeRedemptionParameters.cs, src/Microsoft.Identity.Web.TokenAcquisition/ITokenAcquisitionInternal.cs, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs, tests/DevApps/WebAppCallsMicrosoftGraph/Startup.cs, tests/Microsoft.Identity.Web.Test/AuthCodeRedemptionParametersTests.cs
```csharp
services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme,
options => {
var previous = options.Events.OnAuthorizationCodeReceived;
options.Events.OnAuthorizationCodeReceived = async context =>
{
// In the case you want to change the tenant ID based on the MyApp query parameter:
context.ProtocolMessage.DomainHint = "{yourTenantID}";
await previous(context);
};
});
```
=> add tenant for myApps scenario

src/Microsoft.Identity.Web.TokenAcquisition/AspNetCore/MicrosoftIdentityAppCallingWebApiAuthenticationBuilder.cs, src/Microsoft.Identity.Web.TokenCache/Distributed/DistributedTokenCacheAdapterExtension.cs, src/Microsoft.Identity.Web.TokenCache/InMemory/InMemoryTokenCacheProviderExtension.cs
=> add tryAdd

Directory.Build.props
=> Update MSAL and IdentityModel

src/Microsoft.Identity.Web.TokenAcquisition/MicrosoftIdentityAppCallingWebApiAuthenticationBuilder.cs
conditional compile for targets
=> Move type out of aspnetcore folder

src/Microsoft.Identity.Web/CookiePolicyOptionsExtensions.cs
Address a bug caused by extra space in regex.
=> Fix regex bug

tests/IntegrationTests/TokenAcquirerTests/TokenAcquirer.cs
update test to reflect current users and change condition to avoid future updates
=> Integration test update

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
Provides an implementation for the problem described in #2222 2222
=> Process composite OBO tokens

tests/DevApps/GenericWebApi/Controllers/AuthorizationHeader.cs, tests/DevApps/GenericWebApi/Controllers/DownstreamApi.cs, tests/DevApps/GenericWebApi/Program.cs, tests/DevApps/GenericWebApi/Properties/launchSettings.json, tests/DevApps/GenericWebApi/WeatherForecast.cs, tests/DevApps/GenericWebApi/appsettings.Development.json, tests/DevApps/GenericWebApi/appsettings.json, tests/DevApps/GenericWebApi/webApi.csproj, tests/DevApps/GenericWebApi/webApi.sln
Sample associated with the article: https://github.com/AzureAD/microsoft-identity-web/wiki/generic-api
=> Generic Web API

src/Microsoft.Identity.Web.GraphServiceClient/GraphServiceClientOptions.cs, tests/DevApps/WebAppCallsMicrosoftGraph/WebAppCallsMicrosoftGraph.csproj
I accidentally pushed the sample changes, so this addresses those
=> fix sample

src/Microsoft.Identity.Web.GraphServiceClient/GraphAuthenticationProvider.cs, src/Microsoft.Identity.Web.GraphServiceClient/Readme.md, src/Microsoft.Identity.Web.GraphServiceClient/RequestOptionsExtension.cs, tests/DevApps/WebAppCallsMicrosoftGraph/Pages/AllApps.cshtml.cs, tests/DevApps/WebAppCallsMicrosoftGraph/Pages/AllUsers.cshtml.cs, tests/DevApps/WebAppCallsMicrosoftGraph/Pages/Index.cshtml.cs
For details see https://github.com/AzureAD/microsoft-identity-web/blob/jmprieur/MoreModifiers/src/Microsoft.Identity.Web.GraphServiceClient/Readme.md
=> Adding GraphServiceClient modifiers (WithAppOnly, WithSCopes, ....)

src/Microsoft.Identity.Web.GraphServiceClient/GraphAuthenticationProvider.cs, tests/DevApps/daemon-app/Daemon-app/Daemon-app.csproj, tests/DevApps/daemon-app/Daemon-app/Program.cs
#Fix the Graph5 authentication
=> Fix the Graph5 authentication

Directory.Build.props
=> add for all frameworks

ProjectTemplates/AspNetCoreMicrosoftIdentityWebProjectTemplates.csproj, ProjectTemplates/test-aspnet-templates-from-nuget.bat, ProjectTemplates/test-templates-from-nuget.bat, ProjectTemplates/test-templates.bat, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/DaemonConsoleCallingDownstreamApi.csproj, tests/DevApps/daemon-app/daemon-console-calling-msgraph/DaemonConsoleCallingMsGraph.csproj, tests/DevApps/daemon-app/minimal-web-api/MinimalWebApi.csproj
=> update from 2.12.2 to 2.12.3

tools/app-provisioning-tool/app-provisioning-lib/MicrosoftIdentityPlatformApplication/MicrosoftIdentityPlatformApplicationManager.cs
Fix the case where the scopes are .default in the app sync tool
=> Fix the case where the scopes are .default in the app sync tool

build/template-pack-and-sign-nuget.yaml, tests/Directory.Build.props
Updating lab api package version to resolve cert lookup issues when running on a machine with an expired version of the desired cert.
{Detail}
=> Updating lab api package version and ESRP config

changelog.md
List what changed in the latest Id Web update.
{Detail}
=> 2.13.3 changelog notes

src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs
- the CIAM authority is propagated to the options
- it's a v2.0 authority for JwtBearer
- The metadata endpoint is computed, including when extra query parameters.
Do not merge before MSAL.NET fixes https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4191
=> Improve the processing of CIAM tenants in Web APIs:

src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
- [x ] You've read the [Contributor Guide](https://github.com/AzureAD/microsoft-identity-web/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/AzureAD/microsoft-identity-web/blob/master/CODE_OF_CONDUCT.md).
=> Update XML comments

src/Microsoft.Identity.Web.OWIN/OwinTokenAcquisitionHost.cs
OWIN Token Acquisition is missing implementation of SetSession function which is used by the Hybrid SPA. This change adds implementation using either sessions (if enabled) or OwinContext.
=> [OWIN] Implement SetSession

changelog.md
=> Changelog for 2.13.4

src/Microsoft.Identity.Web.TokenAcquisition/Constants.cs, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs
=> Add revoked cert condition

changelog.md
=> updating changelog

Directory.Build.props, src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs, src/Microsoft.Identity.Web.GraphServiceClient/GraphAuthenticationProvider.cs
Changes that address breaking changes in Abstractions 5
=> Edits addressing changes in abstractions 5

changelog.md
See [changelog.md](https://github.com/AzureAD/microsoft-identity-web/pull/2500/files#diff-3bd14d078188074c410028847113ceae68865d0ad5b844a27183ef87fbe2fcc3)
=> Update changelog.md for 2.15.0

Directory.Build.props
Updated the build.props file to reflect the latest IdentityModel versions
=> Update to latest IdentityModel version

changelog.md
=> Changelog 2.15.1

src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs
=> undo changes, wait on all delegates

Directory.Build.props
=> Update Wilson Version for net8.0

changelog.md
=> Updates changelog.md for 2.15.2

CONTRIBUTING.md
Adapted the team contributing guide for the purposes of idweb.
=> Add new contributing.md

CONTRIBUTING.md
Add link to the building and testing doc.
=> add link to build and testing doc

Directory.Build.props
=> update Azure Identity to 1.10.2

.github/ISSUE_TEMPLATE/bug_report.yml
using `untriaged,needs attention`
=> update bug report with default tags

src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj, src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj, src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
Remove System.Text.Encodings.Web where it is inbox.
=> Remove inbox dependencies

src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs, tests/Microsoft.Identity.Web.Test/ServiceCollectionExtensionsTests.cs
=> Allow user to specify an ICredentialsLoader 

Directory.Build.props, src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj, src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj, src/Microsoft.Identity.Web/CompatibilitySuppressions.xml, tests/Directory.Build.props, tools/Directory.Build.props
https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/baseline-version-validator
Fixes #2572
=> Enable package validation

src/Microsoft.Identity.Web.DownstreamApi/DownstreamApi.cs, src/Microsoft.Identity.Web.GraphServiceClient/MicrosoftGraphExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs, src/Microsoft.Identity.Web.TokenAcquisition/MicrosoftIdentityBaseAuthenticationBuilder.cs, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquirerFactory.cs, src/Microsoft.Identity.Web.TokenAcquisition/WebApiBuilders.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/DownstreamWebApiExtensions.cs, src/Microsoft.Identity.Web/DownstreamWebApiSupport/MicrosoftIdentityAuthenticationMessageHandlerHttpClientBuilderExtensions.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilder.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration.cs, src/Microsoft.Identity.Web/WebApiExtensions/MicrosoftIdentityWebApiServiceCollectionExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppServiceCollectionExtensions.cs
=> Attempt to have better trimmability on .NET 8

tools/app-provisioning-tool/Directory.Build.props, tools/app-provisioning-tool/app-provisioning-lib/app-provisioning-lib.csproj, tools/app-provisioning-tool/app-provisioning-tool/msidentity-app-sync.csproj
=> fix appsync tool version

src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj, src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj
=> Only use IM7 transitive deps for net8+

src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/CookiePolicyOptionsExtensionsTests.cs
https://github.com/aspnet/Announcements/issues/508
=> make updates for .NET 8

tests/DevApps/B2CWebAppCallsWebApi/Client/appsettings.json, tests/DevApps/B2CWebAppCallsWebApi/TodoListService/appsettings.json, tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json, tests/Directory.Build.props, tests/IntegrationTests/SimulateOidc/Properties/launchSettings.json, tests/IntegrationTests/WebAppUiTests/B2CWebAppCallsWebApiLocally.cs, tests/IntegrationTests/WebAppUiTests/TestingWebAppLocally.cs, tests/IntegrationTests/WebAppUiTests/UiTestHelpers.cs, tests/IntegrationTests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs, tests/IntegrationTests/WebAppUiTests/WebAppUiTests.csproj, tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs
Created new UI integration test for B2C apps.
Refactored some existing UI helpers methods to increase flexibility and updated relevant references.
Added a common Xunit collection for the UI tests to keep them from running in parallel when running all tests in the project.
=> Playwright B2C E2E test automation

Directory.Build.props, tests/DevApps/B2CWebAppCallsWebApi/TodoListService/Properties/launchSettings.json, tests/DevApps/aspnet-mvc/OwinWebApi/Web.config, tests/DevApps/aspnet-mvc/OwinWebApi/appsettings.json, tests/DevApps/aspnet-mvc/OwinWebApp/Web.config, tests/IntegrationTests/TokenAcquirerTests/CertificateRotationTest.cs
=> Updating to Wilson7

Directory.Build.props
https://github.com/AzureAD/microsoft-identity-web/issues/2605
=> Fix asp.net core 3.1

src/Microsoft.Identity.Web.TokenAcquisition/IDWebErrorMessage.cs
=> fix typo for error message

RELEASES.md
=> Update RELEASES.md to remove un-necessary instructions about semantic versionning

src/Microsoft.Identity.Web.OWIN/OwinTokenAcquisitionHost.cs
=> respect passed in user argument

Directory.Build.props
related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2184
=> change langVer to 12

changelog.md
=> Changelog for IdWeb 2.17.0

tests/DevApps/ciam/myWebApi/myWebApi.csproj, tests/DevApps/ciam/myWebApp/Pages/Index.cshtml.cs, tests/DevApps/ciam/myWebApp/Program.cs, tests/DevApps/ciam/myWebApp/myWebApp.csproj
Address some of the warnings in Id Web by updating some calls to obsolete code
=> stop using obsolete DownstreamWebApi, use the latest id web

NuGet.Config, src/Microsoft.Identity.Web/NuGet.Config
What?
Moves NuGet.Config into root folder
=> Moves NuGet.Config into root folder

.github/workflows/benchmark-action.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dotnetcore.yml
=> Update rel/v2 workflows

tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
Same as https://github.com/AzureAD/microsoft-identity-web/pull/2708 but for rel/v2
=> Fix user assigned MSI in tests

tests/DevApps/WebAppCallsWebApiCallsGraph/Client/Controllers/HomeController.cs, tests/DevApps/WebAppCallsWebApiCallsGraph/Client/appsettings.json, tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService/TodoListService.csproj, tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json, tests/DevApps/WebAppCallsWebApiCallsGraph/gRPC/appsettings.json, tests/DevApps/aspnet-mvc/OwinWebApi/appsettings.json, tests/DevApps/blazorwasm2-b2c-hosted/Client/Properties/launchSettings.json, tests/DevApps/blazorwasm2/Client/Program.cs, tests/DevApps/blazorwasm2/Server/appsettings.json, tests/DevApps/daemon-app/Daemon-app/Program-net60.cs, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/appsettings.json, tests/DevApps/daemon-app/minimal-web-api/appsettings.json, tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs, tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs, tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
=> Update the appId

tests/DevApps/AzureFunctions/SampleFunc/appsettings.json, tests/DevApps/WebAppCallsWebApiCallsGraph/Client/Controllers/HomeController.cs, tests/DevApps/WebAppCallsWebApiCallsGraph/Client/appsettings.json, tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService/appsettings.json, tests/DevApps/WebAppCallsWebApiCallsGraph/gRPC/appsettings.json, tests/DevApps/aspnet-mvc/OwinWebApi/appsettings.json, tests/DevApps/blazorwasm2/Client/Program.cs, tests/DevApps/blazorwasm2/Server/appsettings.json, tests/DevApps/daemon-app/Daemon-app/Program-net60.cs, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/appsettings.json, tests/DevApps/daemon-app/minimal-web-api/appsettings.json, tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs, tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs, tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
Same as https://github.com/AzureAD/microsoft-identity-web/pull/2715, but for rel/v2
=> Fix web API test app and UI tests

src/Microsoft.Identity.Web.UI/CompatibilitySuppressions.xml
=> Fix Microsoft.Identity.UI supression file

tests/E2E Tests/WebAppUiTests/B2CWebAppCallsWebApiLocally.cs, tests/E2E Tests/WebAppUiTests/WebAppUiTests.csproj
=> Don't run b2c tests on ado

benchmark/Directory.Build.props, build/template-install-dependencies.yaml, tests/Directory.Build.props, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
Updating lab api to 0.12.2
{Detail}
=> Updating lab api to 0.12.2

tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs
Updating constants for lab apps
Working build: https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1281280&view=results
=> Updating constants for lab apps

benchmark/Directory.Build.props, build/template-install-dependencies.yaml, tests/Directory.Build.props, tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
Cherry picking updates from master to update lab api/lab app changes
=> Update rel/v2 with lab api/lab app changes

build/template-restore-build-MSIdentityWeb.yaml, tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs
=> Reactivate tests using labs requiring admin consent

src/Microsoft.Identity.Web.TokenAcquisition/DefaultTokenAcquirerFactoryImplementation.cs, tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
DefaultTokenAcquirerFactoryImplementation now supports multiple regions and more thread safe.
- The DefaultTokenAcquirerFactoryImplementation now incorporates the region within the key string, resolving a bug wherein getting a token acquirer for a particular region could inadvertently yield a token acquirer meant for a different region. 
- Additionally, the implementation now employs a ConcurrentDictionary to manage its data, enhancing thread safety in scenarios where multiple threads may attempt to create a TokenAcquirer simultaneously.
=> DefaultTokenAcquirerFactoryImplementation use ConcurrentDictionary

build/template-restore-build-MSIdentityWeb.yaml, tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs
bringing over @jmprieur 's changes which were applied to rel/v2
=> Reactivate tests using labs requiring admin consent (#2760)

Directory.Build.props
Update Msal and Azure.Identity
=> Update Msal and Azure.Identity

Directory.Build.props
Update Msal and Azure.Identity
=> update msal and azure identity

benchmark/Directory.Build.props, tests/Directory.Build.props, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
Updating Lab.Api to 0.13.1 to fix concurrency issue with tests
=> Updating Lab.Api to 0.13.1

Directory.Build.props
=> Update azure.security libraries to 4.6.0

Directory.Build.props, src/Microsoft.Identity.Web.DownstreamApi/DownstreamApiExtensions.cs, tests/DevApps/WebAppCallsWebApiCallsGraph/Client/Startup.cs, tests/DevApps/WebAppCallsWebApiCallsGraph/Client/appsettings.json
* update abstractions to 5.3.0
* add downstreamApis method
* fix xml
{Detail}
=> update abstractions to 5.3.0 (#2780)

benchmark/TokenAcquisitionBenchmark.cs, src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs, tests/DevApps/aspnet-mvc/OwinWebApi/Web.config, tests/DevApps/aspnet-mvc/OwinWebApp/Web.config, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/DaemonConsoleCallingDownstreamApi.csproj, tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs, tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
there was a bit too much noise to detect signals
=> Clean-up warnings.

src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs
=> fix for fic

tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs, tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
=> Disable the Ciam CUD tests as they don't work any longer since today.

Directory.Build.props, changelog.md
=> remove M.IM 6x references on OWIN

src/Microsoft.Identity.Web.Certificate/KeyVaultCertificateLoader.cs
Added an environment variable to opt out of interactive credentials in KeyVaultCertificateLoader. `IDWEB_DISABLE_INTERACTIVE_AKV_CREDENTIALS` must be set
to "1" or "true" to opt into this behavior.
Fixes #2647
=> Provide an env var to disable interactive auth for KeyVaultCertificateLoader

tools/app-provisioning-tool/Directory.Build.props
=> Update app sync tool to net8,.0

benchmark/Directory.Build.props, tests/Directory.Build.props, tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
=> Fixing build errors

benchmark/Directory.Build.props, tests/Directory.Build.props, tests/Microsoft.Identity.Web.Test.Common/TestConstants.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
=> Updating Lab api and client secret

CodeQL.yaml
Add codeql exclusions for test, benchmark, and docs
=> Create codeql exclusion yaml

src/Microsoft.Identity.Web.TokenAcquisition/ServiceCollectionExtensions.cs, tests/DevApps/aspnet-mvc/OwinWebApi/Web.config, tests/DevApps/aspnet-mvc/OwinWebApp/Web.config
=> In AddTokenAcquisition(singleton:true) an implementation of TokenAcquirerFactory (for ASP.NET Core 2.x on .NET FW) 

src/Microsoft.Identity.Web.GraphServiceClient/GraphAuthenticationProvider.cs, src/Microsoft.Identity.Web.GraphServiceClient/GraphServiceClientOptions.cs, src/Microsoft.Identity.Web.GraphServiceClient/RequestOptionsExtension.cs, src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProviderOption.cs, tests/DevApps/WebAppCallsMicrosoftGraph/Pages/Index.cshtml.cs
Fixes #2855
Tested with End to end test
=>  Adds AddUser to Microsoft Graph request options

src/Microsoft.Identity.Web.GraphServiceClient/GraphAuthenticationProvider.cs, src/Microsoft.Identity.Web.GraphServiceClient/GraphServiceClientOptions.cs, src/Microsoft.Identity.Web.GraphServiceClient/RequestOptionsExtension.cs, src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs, src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProviderOption.cs, src/Microsoft.Identity.Web.TokenAcquisition/BaseAuthorizationHeaderProvider.cs, tests/DevApps/WebAppCallsMicrosoftGraph/Pages/Index.cshtml.cs, tests/E2E Tests/TokenAcquirerTests/BaseAuthorizationHeaderProviderTest.cs
=> Cherry pick #2857 and 2859

build/template-install-dependencies.yaml, build/template-onebranch-release-build.yaml, build/template-pack-and-sign-all-nugets.yaml, build/template-postbuild-code-analysis.yaml, build/template-publish-and-cleanup.yaml, build/template-restore-build-MSIdentityWeb.yaml, build/test-aot.ps1
Move OneBranch scripts from main to rel/v2
=> OneBranch on rel/v2

src/Microsoft.Identity.Web.Certificateless/CompatibilitySuppressions.xml
=> Fix suppression files

benchmark/Directory.Build.props, tests/Directory.Build.props, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
Updating Lab Api to 0.13.3 for relV2
=> Updating Lab Api to 0.13.3 for relV2

benchmark/Directory.Build.props, tests/Directory.Build.props, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
=> Updating Lab Api to 0.13.3

src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj, src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj
DiagnosticSource is inbox on netcoreapp
=> Remove inbox DiagnosticSource

build/pipeline-releasebuild.yaml
I am also happy to delete this. The build will start failing soon because the signing step is deprecated
{Detail}
=> Stop non-OB build from running nightly

src/Microsoft.Identity.Web.TokenAcquisition/DefaultAuthorizationHeaderProvider.cs
Cherry pick 2913 to fix 2912
Fixes #2912
=> Fix 2912 (#2913)

changelog.md
=> Update changelog.md for 2.20.0

benchmark/Directory.Build.props, build/template-install-dependencies.yaml, tests/Directory.Build.props, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
Update for new lab cert and Microsoft.Identity.Lab.Api version
=> Update for new lab cert and Microsoft.Identity.Lab.Api version

benchmark/Directory.Build.props, build/template-install-dependencies.yaml, tests/Directory.Build.props, tools/CrossPlatformValidator/CrossPlatformValidation/Benchmark/Benchmark.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/BenchmarkCSharp/BenchmarkCSharp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CSharpConsoleApp/CSharpConsoleApp.csproj, tools/CrossPlatformValidator/CrossPlatformValidation/CrossPlatformValidatorTests/CrossPlatformValidatorTests.csproj
=> Cherry picks PR 2922: Update Lab cert and Lab Version in use from rel/v2

Directory.Build.props, src/Microsoft.Identity.Web.Certificate/Microsoft.Identity.Web.Certificate.csproj, src/Microsoft.Identity.Web.Certificateless/Microsoft.Identity.Web.Certificateless.csproj, src/Microsoft.Identity.Web.GraphServiceClient/Microsoft.Identity.Web.GraphServiceClient.csproj, src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj, src/Microsoft.Identity.Web.TokenAcquisition/Microsoft.Identity.Web.TokenAcquisition.csproj, src/Microsoft.Identity.Web.TokenCache/Microsoft.Identity.Web.TokenCache.csproj, src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj, tests/DevApps/WebAppCallsMicrosoftGraph/WebAppCallsMicrosoftGraph.csproj, tests/DevApps/aspnet-mvc/OwinWebApi/Web.config, tests/DevApps/aspnet-mvc/OwinWebApp/Web.config, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/DaemonConsoleCallingDownstreamApi.csproj, tests/E2E Tests/GraphServiceClientTests/GraphServiceClientTests.csproj, tests/E2E Tests/NET 7 tests/IntegrationTests/IntegrationTests.csproj, tests/E2E Tests/TokenAcquirerTests/TokenAcquirerTests.csproj, tests/E2E Tests/WebAppUiTests/WebAppUiTests.csproj, tests/Microsoft.Identity.Web.Test.Common/Microsoft.Identity.Web.Test.Common.csproj, tests/Microsoft.Identity.Web.Test.Integration/Microsoft.Identity.Web.Test.Integration.csproj, tests/Microsoft.Identity.Web.Test/Microsoft.Identity.Web.Test.csproj, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Benchmark/Microsoft.Identity.Web.Perf.Benchmark.csproj
Cherry picking #2929 into rel/v2 branch
=> [cherry-pick] fix CVEs (#2929)

tests/DevApps/blazorwasm-b2c/blazorwasm2-b2c.csproj
updating sample dependency to follow component governance guidelines
=> Lozensky/update deps for CVE

build/release-provisioning-tool.yml, build/template-pack-and-sign-all-nugets.yaml
=> Removing reference to Iddp Code Signing

build/release-provisioning-tool.yml, build/template-pack-and-sign-all-nugets.yaml
=> Removing reference to Iddp Code Signing rel v2

src/Microsoft.Identity.Web/CookiePolicyOptionsExtensions.cs, tests/Microsoft.Identity.Web.Test/CookiePolicyOptionsExtensionsTests.cs
Check that regex succeeded and value is an integer.
This fixes the format exception, there may be more work to check for SameSite.
Fixes #2879
=> Check that regex succeeded and value is an integer.

build/template-install-dependencies.yaml
Updating to AzureKeyVault@2 from 1 to fix Id Web build
=> Updating AzureKeyVault task to version 2

tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs
Disable ciam test
Opened #2982 to track
=> Disable ciam test

tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs, tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
=> skip more CIAM E2E tests

tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
=> remove grpc in E2E test

tests/E2E Tests/WebAppUiTests/TestingWebAppLocally.cs, tests/E2E Tests/WebAppUiTests/WebAppCallsApiCallsGraphLocally.cs
=> reenable other ciam test

src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs, src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs, tests/Microsoft.Identity.Web.Test/WebAppExtensionsTests.cs
=> Fix Id Web Build

src/Microsoft.Identity.Web.TokenAcquisition/DefaultAuthorizationHeaderProvider.cs, src/Microsoft.Identity.Web.TokenAcquisition/MergedOptions.cs, tests/DevApps/aspnet-mvc/OwinWebApi/Web.config, tests/DevApps/aspnet-mvc/OwinWebApp/Web.config, tests/Microsoft.Identity.Web.Test.Common/Mocks/QueryStringParser.cs
=> Fix warnings

.github/workflows/dotnetcore.yml, Directory.Build.props, tests/DevApps/Directory.Build.props
=> Update to 9.0.100-rc.1

.gitignore, tests/DevApps/aspnet-mvc/OwinWebApi/OwinWebApi.csproj, tests/DevApps/aspnet-mvc/OwinWebApp/OwinWebApp.csproj, tests/Directory.Build.props, tests/PerformanceTests/PerformanceTestService/PerformanceTestService.csproj, tools/app-provisioning-tool/app-provisioning-lib/app-provisioning-lib.csproj, tools/app-provisioning-tool/tests/Tests.csproj
=> Upgrading vulnerable packages

tests/Directory.Build.props, tests/PerformanceTests/PerformanceTestService/PerformanceTestService.csproj
=> Addressing Brett's PR feedback

tests/DevApps/aspnet-mvc/OwinWebApi/OwinWebApi.csproj, tests/DevApps/aspnet-mvc/OwinWebApp/OwinWebApp.csproj
=> Collapse PackageReferences

build/template-install-dependencies.yaml
This addresses the OneBranch build failure
=> update net 9 version to rc 1 in build script

tests/Directory.Build.props, tests/E2E Tests/GraphServiceClientTests/GraphServiceClientTests.cs, tests/E2E Tests/WebAppUiTests/WebAppIntegrationTests.cs, tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs, tests/Microsoft.Identity.Web.Test/Certificates/DefaultCertificateLoaderTests.cs, tests/Microsoft.Identity.Web.Test/DownstreamWebApiSupport/DownstreamApiTests.cs, tests/Microsoft.Identity.Web.Test/MicrosoftIdentityOptionsTests.cs, tests/Microsoft.Identity.Web.Test/Resource/JwtBearerMiddlewareDiagnosticsTests.cs, tests/Microsoft.Identity.Web.Test/Resource/OpenIdConnectMiddlewareDiagnosticsTests.cs, tests/Microsoft.Identity.Web.Test/Resource/RequiredScopeOrAppPermissionPolicyTests.cs, tests/Microsoft.Identity.Web.Test/Resource/RequiredScopePolicyTests.cs, tests/Microsoft.Identity.Web.Test/TokenAcquisitionAuthorityTests.cs
Updated XUnit package versions, all tests working locally after the update.
=> update xunit versions

build/credscan-exclusion.json
tested and this fixed the release build
=> fix cred scan

Directory.Build.props
- reference Wilson 8.1.2
- Update the release notes
=> Updates for Microsoft.Identity.Web 3.2.2

Directory.Build.props
=> update system.Text.Json to 8.0.5 CVE-2024-43485

.github/workflows/dotnetcore.yml, Directory.Build.props, build/template-install-dependencies.yaml, tests/DevApps/Directory.Build.props
=> Update .NET 9 to RC 2

.github/workflows/dotnetcore.yml, tests/Microsoft.Identity.Web.Test/CacheEncryptionTests.cs
Fix EncryptionTestAsync on .NET 9
Fix GitHub Action naming.
=>  Fix EncryptionTestAsync on .NET 9

.github/dependabot.yml, src/Microsoft.Identity.Web.OWIN/Microsoft.Identity.Web.OWIN.csproj, tests/DevApps/aspnet-mvc/OwinWebApi/OwinWebApi.csproj, tests/DevApps/ciam/myWebApi/myWebApi.csproj, tests/DevApps/ciam/myWebApp/myWebApp.csproj, tools/app-provisioning-tool/app-provisioning-lib/app-provisioning-lib.csproj
Upgrading versions in files identified by dependabot.
=> Upgrade versions

Directory.Build.props
Upgrading MSAL (Microsoft.Identity.Client) to 4.66.1
=> Upgrading MSAL version

JsonSchemas/Credentials.json, JsonSchemas/microsoft-identity-web.json
To use it:
Add this at the top of your appsettings.json, in the main block:
"$schema": "https://raw.githubusercontent.com/AzureAD/microsoft-identity-web/refs/heads/jmprieur/jsonschema/JsonSchemas/microsoft-identity-web.json",
=> Adding a json schema for Microsoft.Identity.Web configuration

build/template-install-dependencies.yaml
Install all .NET versions in pipeline to fix run tests task. Partially reverts 1e955bfec45d779763c954fd1b8adf015f23c053.
=> Install all .NET versions in pipeline to fix run tests task

build/template-install-dependencies.yaml, global.json
=> Specify sdk version in global.json

Directory.Build.props, build/template-publish-and-cleanup.yaml, src/Microsoft.Identity.Web.GraphServiceClientBeta/Microsoft.Identity.Web.GraphServiceClientBeta.csproj, src/Microsoft.Identity.Web.MicrosoftGraphBeta/Microsoft.Identity.Web.MicrosoftGraphBeta.csproj, tests/DevApps/AjaxCallActionsWithDynamicConsent/AjaxCallActionsWithDynamicConsent.csproj, tests/DevApps/Directory.Build.props, tests/DevApps/aspnet-mvc/OwinWebApi/Web.config, tests/DevApps/daemon-app/Daemon-app/Daemon-app.csproj, tests/DevApps/daemon-app/daemon-console-calling-downstreamApi/DaemonConsoleCallingDownstreamApi.csproj, tests/DevApps/daemon-app/daemon-console-calling-msgraph/DaemonConsoleCallingMsGraph.csproj, tests/Directory.Build.props, tests/E2E Tests/GraphServiceClientTests/GraphServiceClientTests.csproj, tests/E2E Tests/IntegrationTestService/IntegrationTestService.csproj, tests/E2E Tests/NET 7 tests/IntegrationTests/IntegrationTests.csproj, tests/E2E Tests/NET 7 tests/WebApp/WebApp.csproj, tests/E2E Tests/SimulateOidc/SimulateOidc.csproj, tests/E2E Tests/TokenAcquirerTests/TokenAcquirerTests.csproj, tests/Microsoft.Identity.Web.Test.Common/Microsoft.Identity.Web.Test.Common.csproj, tests/Microsoft.Identity.Web.Test.Integration/Microsoft.Identity.Web.Test.Integration.csproj, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Benchmark/Microsoft.Identity.Web.Perf.Benchmark.csproj, tests/PerformanceTests/Microsoft.Identity.Web.Perf.Client/Microsoft.Identity.Web.Perf.Client.csproj, tests/PerformanceTests/PerformanceTestService/PerformanceTestService.csproj, tools/ConfigureGeneratedApplications/ConfigureGeneratedApplications.csproj
Passing [OneBranch build](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1408909&view=results)
=> fix warnings in idweb and readd warnings as errors

.github/workflows/aot-check.yml, .github/workflows/dotnetcore.yml
Required to prevent build failures due to the upcoming CDN changes
see https://github.com/dotnet/core/issues/9671
=> Update dotnet actions

.github/workflows/dotnetcore.yml
fixes #3147 
The last few builds for PRs have taken 15-16 minutes. The build for this change took ~13 minutes.
=> add flags back to avoid multiple builds

Directory.Build.props
=> Update the IdWeb version number

tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
=> More tests fixes

Directory.Build.props
=> Update to MSAL 4.70.0

CONTRIBUTING.md, README.md, SECURITY.md, changelog.md, tools/app-provisioning-tool/README.md
https://github.com/AzureAD/microsoft-identity-web/issues/3322
=> PR suggestions from copilot

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/scripts/container-creation.sh, .vscode/settings.json
=> Add devcontainer

Directory.Build.props
#Update Directory.Build.Props to 3.8.5
{Detail}
=> Update Directory.Build.Props to 3.8.5

src/Microsoft.Identity.Web.UI/CompatibilitySuppressions.xml, src/Microsoft.Identity.Web.UI/Microsoft.Identity.Web.UI.xml
- [*] You've read the [Contributor Guide](https://github.com/AzureAD/microsoft-identity-web/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/AzureAD/microsoft-identity-web/blob/master/CODE_OF_CONDUCT.md).
- [*] You've included unit or integration tests for your change, where applicable.
- [*] You've included inline docs for your change, where applicable.
- [*] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
{Detail}
=> Changes to GlobalSuppressionFile to fix the PR build failures introduced after merging PR #3330

Microsoft.Identity.Web.slnLaunch, changelog.md, src/Microsoft.Identity.Web.DownstreamApi/DownstreamApiExtensions.cs
- Release notes
- cleaned-up un-necessary instruction in DownstreamApis
- Started adding a slnLaunch
See #3366 3117
=> Release notes and cleanup

Directory.Build.props, tests/Directory.Build.props, tools/app-provisioning-tool/app-provisioning-lib/app-provisioning-lib.csproj
=> Remove invalid comparisons

src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs, src/Microsoft.Identity.Web/MicrosoftIdentityConsentAndConditionalAccessHandler.cs, tests/DevApps/WebAppCallsWebApiCallsGraph/TodoListService/Controllers/TodoListController.cs, tests/Microsoft.Identity.Web.Test/AzureADB2COpenIDConnectEventHandlersTests.cs
The following CodeQL issues are suppressed: 
[[SM00405] URL redirection from remote source](https://codeql.microsoft.com/issues/2ca7db29-2f0d-4c54-ba14-04a864d96a96?copilot_promptid=E91B0CE9-0C1B-4AC2-8A46-33F49B67E058) (ConsentAndConditionalAccessHandler)
[[SM00405] URL redirection from remote source](https://codeql.microsoft.com/issues/58fa55f0-c07b-4117-8a8e-82692ff259a7?copilot_promptid=E91B0CE9-0C1B-4AC2-8A46-33F49B67E058) (ConsentAndConditionalAccessHandler)
[[SM00405] URL redirection from remote source](https://codeql.microsoft.com/issues/60c19644-c596-43b6-aafb-c4c846abd3bd?copilot_promptid=E91B0CE9-0C1B-4AC2-8A46-33F49B67E058) (AzureADB2COpenIDConnectEventHandlersTests.cs)
[[SM03781] Server Side Request Forgery (SSRF)](https://codeql.microsoft.com/issues/53b4ca02-d91f-48e1-a5a9-ef …
=> Suppress codeql issues

tests/E2E Tests/TokenAcquirerTests/TokenAcquirer.cs
=> Fix additional E2E tests broken by lab outage

src/Microsoft.Identity.Web.Sidecar/README.md
=> Add readme

src/Microsoft.Identity.Web.Sidecar/AppJsonSerializerContext.cs, src/Microsoft.Identity.Web.Sidecar/CacheControl.cs, src/Microsoft.Identity.Web.Sidecar/Directory.Build.props, src/Microsoft.Identity.Web.Sidecar/Endpoints/AuthorizationHeaderEndpoint.cs, src/Microsoft.Identity.Web.Sidecar/Endpoints/DownstreamApiEndpoint.cs, src/Microsoft.Identity.Web.Sidecar/Endpoints/ValidateRequestEndpoints.cs, src/Microsoft.Identity.Web.Sidecar/Microsoft.Identity.Web.Sidecar.csproj, src/Microsoft.Identity.Web.Sidecar/Models/AuthorizationHeaderRequest.cs, src/Microsoft.Identity.Web.Sidecar/Models/DownstreamApiRequest.cs, src/Microsoft.Identity.Web.Sidecar/OptionsOverrideSchemaTransformer.cs, src/Microsoft.Identity.Web.Sidecar/Program.cs, src/Microsoft.Identity.Web.Sidecar/Properties/launchSettings.json
Incremental work on making this sidecar trimmable. Some of the other dependencies in ID web prevent fully trimming
=> Make the sidecar trim friendlier

tests/DevApps/SidecarAdapter/python/MicrosoftIdentityWebSidecarClient.py, tests/DevApps/SidecarAdapter/python/main.py
Adds new option from new api parameter
=> Update python adapter

src/Microsoft.Identity.Web.Sidecar/Microsoft.Identity.Web.Sidecar.csproj
=> Don't use R2R for sidecar
